import {test} from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {Miniflare,convertV4MiniflareOptions} from 'miniflare'
import {ApifyAdapter,apifyId,apifySecret,acquisitionBounds,profileInput,ACQUISITION_SLOTS} from '../src/apify'
import {configureActor,reviewActor,createAcquisition,actorRegistry,acquisitionHistory,cancelAcquisition,actorResource} from '../src/acquisition'
import {registryStatus,requireEnabled} from '../src/providers'
import {runJobs} from '../src/jobs'
import {stmt,one,all} from '../src/db'
import {digest,qualifyAcquiredDemand} from '../src/core'
import app from '../src/index'

// Synthetic fixtures only. No Apify credits are spent by this test suite.
const TOKEN='fixture-apify-secret-not-live',ACTOR='fixtureActor01',BUILD='fixtureBuild01',VIDEO='abcdefghijk'
const schema={type:'object',required:['startUrls'],properties:{startUrls:{type:'array'},maxComments:{type:'integer'},sortCommentsBy:{type:'string',enum:['NEWEST_FIRST','TOP_COMMENTS']},oldestCommentDate:{type:'string'}}}
const actor={id:ACTOR,username:'fixture',name:'comments',title:'Fixture comments',isPublic:true,actorPermissionLevel:'LIMITED_PERMISSIONS',taggedBuilds:{latest:{buildId:BUILD}},pricingInfos:[{pricingModel:'PAY_PER_EVENT',startedAt:'2026-01-01T00:00:00Z',minimalMaxTotalChargeUsd:0.5,pricingPerEvent:{actorChargeEvents:{result:{eventPriceUsd:0.002,isPrimaryEvent:true}}}}]}
const build={id:BUILD,actId:ACTOR,status:'SUCCEEDED',buildNumber:'0.0.1',inputSchema:JSON.stringify(schema),readme:'Public comments for authorized usage; review terms.',actorDefinition:{minMemoryMbytes:256}}
const defaultBounds=()=>({query:'https://www.youtube.com/watch?v='+VIDEO,max_items:5,max_pages:1,timeout_seconds:120,max_charge_usd:0.5,date_from:new Date(Date.now()-7*86400000).toISOString().slice(0,10),date_to:new Date().toISOString().slice(0,10)})
function mockedProvider(options:any={}){
 const requests:{url:string;method:string;body:any}[]=[],runs=new Map<string,any>();let starts=0,aborts=0
 const mock=async(u:any,init:RequestInit={})=>{
  const url=new URL(String(u)),method=init.method||'GET';assert.equal(url.hostname,'api.apify.com');assert.equal(new Headers(init.headers).get('Authorization'),'Bearer '+TOKEN);assert.equal(init.redirect,'manual');assert.ok(!url.href.includes(TOKEN));requests.push({url:url.href,method,body:init.body?JSON.parse(String(init.body)):null});
  if(url.pathname==='/v2/users/me')return Response.json({data:{id:'fixtureUser'}})
  if(url.pathname==='/v2/store')return Response.json({data:{items:[actor]}})
  if(url.pathname.startsWith('/v2/acts/')&&method==='GET')return Response.json({data:options.actor||actor})
  if(url.pathname.startsWith('/v2/actor-builds/'))return Response.json({data:options.build||build})
  if(url.pathname.endsWith('/runs')&&method==='POST'){
   starts++;if(options.startTimeout)throw Error(TOKEN)
   assert.equal(url.searchParams.get('maxTotalChargeUsd'),'0.5');assert.equal(url.searchParams.get('timeout'),'120');assert.equal(url.searchParams.get('build'),'0.0.1');assert.equal(url.searchParams.get('forcePermissionLevel'),'LIMITED_PERMISSIONS');assert.equal(requests.at(-1)!.body.maxComments,5)
   const r={id:'fixtureRun'+starts,actId:ACTOR,buildId:BUILD,status:'RUNNING',defaultDatasetId:'fixtureDataset'+starts,usageTotalUsd:0,usage:{ACTOR_COMPUTE_UNITS:0}};runs.set(r.id,r);return Response.json({data:r})
  }
  if(url.pathname.endsWith('/abort')){aborts++;return Response.json({data:{status:'ABORTING'}})}
  if(url.pathname.startsWith('/v2/actor-runs/')){const rid=url.pathname.split('/').at(-1)!,r=runs.get(rid);return Response.json({data:{...r,status:options.runStatus||'SUCCEEDED',usageTotalUsd:options.actualUsage??0.004}})}
  if(url.pathname.includes('/datasets/'))return Response.json(options.rows||[{cid:'comment1',comment:'I need a workflow tool for our team',author:'fixture',videoId:VIDEO},{cid:'comment2',comment:'Lovely music today',author:'fixture2',videoId:VIDEO}])
  throw Error('Unexpected fixed API route')
 }
 return {mock,requests,get starts(){return starts},get aborts(){return aborts}}
}
async function database(fn:(env:any)=>Promise<void>){
 const mf=new Miniflare(convertV4MiniflareOptions({modules:true,script:'export default {fetch(){return new Response("ok")}}',d1Databases:['DB'],compatibilityDate:'2026-03-01'}));
 try{const DB=await mf.getD1Database('DB') as any;for(const name of ['0001_initial.sql','0002_provider_registry.sql','0003_apify_acquisition.sql','0004_acquisition_provider_configs.sql'])await DB.exec(readFileSync(new URL('../migrations/'+name,import.meta.url),'utf8').replace(/\n/g,' '));await DB.batch([stmt(DB,'INSERT INTO users VALUES (?,?,?,?,?)','u','apify@example.test','QA','hash',Date.now()),stmt(DB,"INSERT INTO workspaces (id,name,created_at) VALUES ('w','QA',?)",Date.now()),stmt(DB,"INSERT INTO workspaces (id,name,created_at) VALUES ('other','Other QA',?)",Date.now()),stmt(DB,"INSERT INTO workspace_members VALUES ('w','u','OWNER')"),stmt(DB,"INSERT INTO providers (id,workspace_id,kind,status,enabled,updated_at,validated_at,health_status) VALUES ('w:apify','w','apify','ENABLED',1,?,?,'HEALTHY')",Date.now(),Date.now())]);await fn({DB,APIFY_API_TOKEN:TOKEN})}finally{await mf.dispose()}
}
async function reviewed(env:any){const configured=await configureActor(env,'w','u',{capability:'youtube-comments',profile:'youtube-comments-v1',actor_id:ACTOR});await reviewActor(env,'w','u',configured.id,{confirm:true,terms_authorized:true,review_hash:configured.metadata.review_hash});return actorResource(env,'w',configured.id)}
async function queue(env:any,r:any,key:string,extra:any={}){return createAcquisition(env,'w','u','request',{registry_id:r.id,actor_revision:r.revision,...defaultBounds(),validation_run:true,confirm:true,authorize_spend:true,idempotency_key:key,...extra})}
async function step(env:any){await stmt(env.DB,"UPDATE jobs SET next_run_at=0 WHERE type='ACQUIRE' AND status='QUEUED'").run();await runJobs(env,'w')}

test('Apify slots and input bounds exclude credentials, arbitrary targets and unbounded acquisition',()=>{
 assert.equal(ACQUISITION_SLOTS.length,8);assert.throws(()=>apifySecret({DB:{} as any}));assert.throws(()=>apifyId('https://evil.test'));assert.throws(()=>apifyId('apify_api_FAKE'));
 for(const b of [{max_items:0},{max_items:26},{max_pages:2},{timeout_seconds:0},{max_charge_usd:0},{max_charge_usd:2},{max_charge_usd:undefined},{date_from:'2026-02-30'},{date_from:'2020-01-01'},{query:'apify_api_FAKE'}])assert.throws(()=>acquisitionBounds({...defaultBounds(),...b}));
 assert.equal(acquisitionBounds({...defaultBounds(),max_charge_usd:0.29}).max_charge_usd,0.29);
 for(const query of ['https://youtube.com.evil.test/watch?v='+VIDEO,'http://localhost/private','https://www.youtube.com/channel/example','https://u:password@www.youtube.com/watch?v='+VIDEO])assert.throws(()=>profileInput('youtube-comments-v1',{...acquisitionBounds(defaultBounds()),query}));
 assert.throws(()=>profileInput('metadata-only',acquisitionBounds(defaultBounds())));
})
test('Apify validation/discovery/inspection are read-only and expose safe mutable pricing/schema metadata',async()=>{
 const original=fetch,p=mockedProvider();try{globalThis.fetch=p.mock;const a=new ApifyAdapter(TOKEN);assert.equal((await a.validateConfiguration()).actor_execution_validated,false);assert.equal((await a.discoverActor('youtube'))[0].status,'DISCOVERED_NOT_VALIDATED');const inspected=await a.inspectActor(ACTOR,'youtube-comments-v1');assert.equal(inspected.validation_status,'SCHEMA_CHECKED_RUN_UNVALIDATED');assert.equal(inspected.pricing.model,'PAY_PER_EVENT');assert.equal(inspected.review_hash.length,64);assert.ok(!JSON.stringify(inspected).includes(TOKEN));assert.equal(p.starts,0)}finally{globalThis.fetch=original}
})
test('Actor compliance, full permission, incompatible schema and non-PPE pricing remain blocked',async()=>{
 const original=fetch;try{for(const options of [{build:{...build,readme:'Bypass API restrictions and platform limits'}},{actor:{...actor,actorPermissionLevel:'FULL_PERMISSIONS'}},{build:{...build,inputSchema:JSON.stringify({...schema,required:['cookies']})}},{build:{...build,actorDefinition:{minMemoryMbytes:1024}}},{actor:{...actor,pricingInfos:[{pricingModel:'FREE'}]}}]){globalThis.fetch=mockedProvider(options).mock;const s=await new ApifyAdapter(TOKEN).inspectActor(ACTOR,'youtube-comments-v1');assert.equal(s.validation_status,'DOCUMENTATION_REQUIRED')}}finally{globalThis.fetch=original}
})
test('Safe Apify auth/permission/rate/timeouts/redirect/oversized payloads never echo token',async()=>{
 const original=fetch;try{for(const [status,code] of [[401,'AUTHENTICATION'],[403,'PERMISSION'],[429,'RATE_LIMIT'],[500,'PROVIDER'],[302,'PROVIDER']] as const){globalThis.fetch=async()=>new Response(JSON.stringify({error:TOKEN}),{status,headers:{Location:'https://evil.test'}});await assert.rejects(()=>new ApifyAdapter(TOKEN).validateConfiguration(),(e:any)=>e.code===code&&!e.message.includes(TOKEN))}globalThis.fetch=async()=>{throw Error(TOKEN)};await assert.rejects(()=>new ApifyAdapter(TOKEN).validateConfiguration(),(e:any)=>e.code==='TIMEOUT'&&!e.message.includes(TOKEN));globalThis.fetch=async()=>Response.json('x'.repeat(1000001));await assert.rejects(()=>new ApifyAdapter(TOKEN).validateConfiguration(),(e:any)=>e.code==='PROVIDER')}finally{globalThis.fetch=original}
})
test('Output normalization preserves source/Actor/run/dataset/input provenance without inventing publication time',async()=>{
 const original=fetch,p=mockedProvider();try{globalThis.fetch=p.mock;const adapter=new ApifyAdapter(TOKEN),a=await adapter.inspectActor(ACTOR,'youtube-comments-v1');const output=await adapter.normalizeOutput(a,{run_id:'run1',dataset_id:'dataset1',status:'SUCCEEDED',actual_usage_usd:0.004},acquisitionBounds(defaultBounds()),[{cid:'c1',videoId:VIDEO,comment:'I need an app'},{cid:'c2',videoId:'xxxxxxxxxxx',comment:'mismatch'},{cid:'c3',videoId:VIDEO,comment:TOKEN}], 'fingerprint');assert.equal(output.records.length,1);assert.equal(output.rejected.length,2);const r=output.records[0];assert.equal(r.provider,'apify');assert.equal(r.verified,false);assert.equal(r.published_at,'');assert.equal(r.external_id,'youtube:'+VIDEO+':c1');assert.equal(r.metadata.freshness,'UNKNOWN_NOT_INFERRED');for(const key of ['source','actorId','actorVersion','buildId','runId','datasetId','inputFingerprint','actualUsage','termsReference','rawReference'])assert.ok(key in r.metadata)}finally{globalThis.fetch=original}
})
test('Mock full acquisition: Actor review → async start → dataset → evidence → qualified opportunity → dedup',async()=>{
 const original=fetch,p=mockedProvider();try{globalThis.fetch=p.mock;await database(async env=>{const r=await reviewed(env),j=await queue(env,r,'first');assert.equal((await queue(env,r,'first')).id,j.id);await assert.rejects(()=>queue(env,r,'first',{max_items:6}));await step(env);assert.equal(p.starts,1);assert.equal((await one(env.DB,'SELECT phase FROM acquisition_jobs WHERE job_id=?',j.id)).phase,'RUNNING');assert.equal((await one(env.DB,'SELECT status FROM jobs WHERE id=?',j.id)).status,'QUEUED');await step(env);const job=await one(env.DB,'SELECT * FROM jobs WHERE id=?',j.id);assert.equal(job.status,'SUCCEEDED',job.error_message);const result=JSON.parse(job.result);assert.equal(result.evidence_count,2);assert.equal(result.qualified_count,1);assert.equal(result.unqualified_count,1);assert.equal(result.actual_usage_usd,0.004);assert.equal((await one(env.DB,'SELECT COUNT(*) n FROM acquisition_signals')).n,2);assert.equal((await one(env.DB,'SELECT version FROM opportunity_scores')).version,'rules-v1.0');assert.equal((await actorRegistry(env,'w')).find(x=>x.capability==='youtube-comments')!.status,'RUN_VALIDATED');const second=await queue(env,await actorResource(env,'w',r.id),'second');await step(env);await step(env);assert.equal(JSON.parse((await one(env.DB,'SELECT result FROM jobs WHERE id=?',second.id)).result).duplicate_count,2);assert.equal((await one(env.DB,'SELECT COUNT(*) n FROM opportunities')).n,1);assert.equal((await one(env.DB,'SELECT COUNT(*) n FROM signals')).n,2);assert.equal((await one(env.DB,'SELECT COUNT(*) n FROM acquisition_signals')).n,4);assert.ok(!JSON.stringify(await acquisitionHistory(env,'w')).includes(TOKEN));assert.ok(!JSON.stringify(await registryStatus(env,'w')).includes(TOKEN));assert.equal((await one(env.DB,"SELECT credential_cipher FROM providers WHERE kind='apify'")).credential_cipher,null);})}finally{globalThis.fetch=original}
})
test('Ambiguous paid POST becomes UNKNOWN and never auto-restarts even on manual retry',async()=>{
 const original=fetch,p=mockedProvider({startTimeout:true});try{globalThis.fetch=p.mock;await database(async env=>{const r=await reviewed(env),j=await queue(env,r,'ambiguous');await step(env);assert.equal(p.starts,1);assert.equal((await one(env.DB,'SELECT phase FROM acquisition_jobs')).phase,'UNKNOWN');assert.equal((await one(env.DB,'SELECT status FROM jobs WHERE id=?',j.id)).status,'FAILED');await stmt(env.DB,"UPDATE jobs SET status='QUEUED',next_run_at=0 WHERE id=?",j.id).run();await step(env);assert.equal(p.starts,1);assert.equal((await one(env.DB,'SELECT phase FROM acquisition_jobs')).phase,'UNKNOWN')})}finally{globalThis.fetch=original}
})
test('Spend approval, reviewed terms, Actor revision, budget reservations and workspace isolation enforced',async()=>{
 const original=fetch,p=mockedProvider();try{globalThis.fetch=p.mock;await database(async env=>{const r=await reviewed(env);for(const extra of [{confirm:false},{authorize_spend:false},{actor_revision:0},{max_charge_usd:0.1},{raw_input:{cookies:'not accepted'}}])await assert.rejects(()=>queue(env,r,'unsafe',extra));await assert.rejects(()=>actorResource(env,'other',r.id));await assert.rejects(()=>requireEnabled({...env,APIFY_API_TOKEN:undefined},'w','apify'));await queue(env,r,'budget-1',{max_charge_usd:1});await assert.rejects(()=>queue(env,r,'budget-2'),(e:any)=>e.code==='RATE_LIMIT');assert.equal((await one(env.DB,'SELECT COUNT(*) n FROM jobs')).n,1);assert.equal(p.starts,0)})}finally{globalThis.fetch=original}
})
test('Cancellation before start makes no paid POST; running abort is confirmed through polling',async()=>{
 const original=fetch,p=mockedProvider();try{globalThis.fetch=p.mock;await database(async env=>{const r=await reviewed(env),first=await queue(env,r,'cancel-before');await cancelAcquisition(env,'w',first.id);await step(env);assert.equal(p.starts,0);assert.equal((await one(env.DB,'SELECT status FROM jobs WHERE id=?',first.id)).status,'CANCELLED');const second=await queue(env,r,'cancel-running');await step(env);await cancelAcquisition(env,'w',second.id);/* Keep original run map; simulate status responses via a wrapper. */const current=globalThis.fetch;globalThis.fetch=async(u,i)=>String(u).includes('/actor-runs/')&&!String(u).endsWith('/abort')?Response.json({data:{id:'fixtureRun1',actId:ACTOR,buildId:BUILD,status:'RUNNING',defaultDatasetId:'fixtureDataset1'}}):current(u,i);await step(env);assert.equal(p.aborts,1);globalThis.fetch=async(u,i)=>String(u).includes('/actor-runs/')?Response.json({data:{id:'fixtureRun1',actId:ACTOR,buildId:BUILD,status:'ABORTED',defaultDatasetId:'fixtureDataset1'}}):current(u,i);await step(env);assert.equal((await one(env.DB,'SELECT status FROM jobs WHERE id=?',second.id)).status,'CANCELLED');assert.equal(p.starts,1)})}finally{globalThis.fetch=original}
})
test('Unauthorized acquisition APIs, no secret in API/DB/errors, enable blocked before live output validation',async()=>{
 const original=fetch,p=mockedProvider();try{globalThis.fetch=p.mock;await database(async env=>{
 const token='fixture-session';await stmt(env.DB,'INSERT INTO sessions VALUES (?,?,?)',await digest(token),'u',Date.now()+60000).run();const pending:Promise<unknown>[]=[];const ctx={waitUntil(p:Promise<unknown>){pending.push(p)},passThroughOnException(){}};
 const req=async(path:string,b?:any,expected=200,cookie=true)=>{const response=await app.request('https://ordvela.test/api'+path,{method:b?'POST':'GET',headers:{'Content-Type':'application/json',...(cookie?{Cookie:'ordvela_session='+token}:{})},...(b?{body:JSON.stringify(b)}:{})},env,ctx as any);assert.equal(response.status,expected);const raw=await response.text();assert.ok(!raw.includes(TOKEN));await Promise.all(pending.splice(0));return JSON.parse(raw).data};
 await req('/acquisitions',undefined,401,false);await req('/acquisitions',{registry_id:'any'},401,false);const registry=await req('/acquisitions/actors');assert.equal(registry.slots.length,8);assert.equal(registry.runtime_configured,true);assert.equal((await req('/providers')).registry.find((x:any)=>x.id==='apify').configured,true);const configured=await req('/acquisitions/actors',{capability:'youtube-comments',actor_id:ACTOR,profile:'youtube-comments-v1',confirm:true},201);await req('/acquisitions/actors/'+encodeURIComponent(configured.id)+'/enable',{confirm:true},409);
 const tables=['actor_registry','acquisition_jobs','jobs','signals','audit_events','providers'];for(const table of tables)assert.ok(!JSON.stringify(await all(env.DB,'SELECT * FROM '+table)).includes(TOKEN));
 })}finally{globalThis.fetch=original}
})

test('Concurrent identical acquisition admission reserves once and returns one stable job',async()=>{
 const original=fetch,p=mockedProvider();try{globalThis.fetch=p.mock;await database(async env=>{const r=await reviewed(env);const [a,b]=await Promise.all([queue(env,r,'concurrent'),queue(env,r,'concurrent')]);assert.equal(a.id,b.id);assert.equal((await one(env.DB,'SELECT COUNT(*) n FROM acquisition_jobs')).n,1);assert.equal((await one(env.DB,'SELECT COUNT(*) n FROM jobs')).n,1);await step(env);assert.equal(p.starts,1)})}finally{globalThis.fetch=original}
})
test('Actor/schema/pricing changes invalidate spending approval before paid start',async()=>{
 const original=fetch,p=mockedProvider();try{globalThis.fetch=p.mock;await database(async env=>{const r=await reviewed(env),j=await queue(env,r,'mutable-price');globalThis.fetch=mockedProvider({actor:{...actor,pricingInfos:[{...actor.pricingInfos[0],minimalMaxTotalChargeUsd:1}]}}).mock;await step(env);assert.equal(p.starts,0);assert.equal((await one(env.DB,'SELECT status FROM jobs WHERE id=?',j.id)).status,'FAILED');assert.equal((await one(env.DB,'SELECT phase FROM acquisition_jobs WHERE job_id=?',j.id)).phase,'FAILED')})}finally{globalThis.fetch=original}
})
test('Dataset partial/empty/malformed and terminal external failure are honest and isolate other providers',async()=>{
 const original=fetch;try{for(const options of [{rows:[{cid:'c1',comment:'I need an app',videoId:VIDEO},{cid:'c2',comment:'mismatch',videoId:'xxxxxxxxxxx'}]},{rows:[]},{rows:[{garbage:true}]},{runStatus:'FAILED'}]){
 const p=mockedProvider(options);globalThis.fetch=p.mock;await database(async env=>{const r=await reviewed(env),j=await queue(env,r,'dataset');await step(env);await step(env);const job=await one(env.DB,'SELECT * FROM jobs WHERE id=?',j.id);if(options.runStatus==='FAILED'||(options.rows?.length===1&&options.rows[0].garbage)){assert.equal(job.status,'FAILED');assert.equal((await one(env.DB,'SELECT phase FROM acquisition_jobs WHERE job_id=?',j.id)).phase,'FAILED');assert.equal((await one(env.DB,'SELECT COUNT(*) n FROM opportunities')).n,0)}else{assert.equal(job.status,'SUCCEEDED');const result=JSON.parse(job.result);assert.equal(result.acquisition_status,options.rows?.length?'PARTIAL':'SUCCEEDED');assert.equal(result.output_validated,!!options.rows?.length)}assert.equal((await requireEnabled(env,'w','hacker-news')).enabled,1);assert.ok(!(await registryStatus(env,'w')).find(x=>x.id==='hacker-news')!.error_code)})
 }}finally{globalThis.fetch=original}
})

test('Acquired evidence categories distinguish interest/discussion/question from commercial demand without score mutation',()=>{
 assert.equal(qualifyAcquiredDemand('I am curious about this app').category,'INTEREST');assert.equal(qualifyAcquiredDemand('Nice music today').category,'DISCUSSION');assert.equal(qualifyAcquiredDemand('How much would it cost to build a workflow app?').category,'COMMERCIAL_INTENT_HYPOTHESIS');assert.equal(qualifyAcquiredDemand('Any alternative to this software?').qualified,true);assert.equal(qualifyAcquiredDemand('We offer an app, buy now, how much?').qualified,false);assert.equal(qualifyAcquiredDemand('Where can I buy a tool?').score_modified,false)
})
