import { chromium } from 'playwright'
import assert from 'node:assert/strict'
import { mkdir,writeFile } from 'node:fs/promises'
const BASE=process.env.TEST_BASE_URL||'http://localhost:3000';
if(!BASE.includes('localhost')&&!process.env.ALLOW_TEST_DATA)throw Error('Browser test creates QA data; use isolated staging only.');
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const errors=[];let checks=0;
const check=(v,msg)=>{assert.ok(v,msg);checks++};
const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();
page.on('pageerror',e=>errors.push(e.message));page.on('console',msg=>{if(msg.type()==='error'&&!msg.text().includes('401 (Unauthorized)')&&!msg.text().includes('500 (Internal Server Error)'))errors.push(msg.text())});
page.on('dialog',async d=>{if(d.type()==='prompt'){await d.accept(d.message().includes('Target')?'QA ONLY browser handoff — no external contact':d.message().includes('Follow')?'2026-12-01':'QA ONLY simulated manual contact, never sent')}else await d.accept()});
try{
  await mkdir('test-results',{recursive:true});
  await page.goto(BASE);await page.waitForSelector('#auth-form');await page.click('#auth-toggle');const email=`browser-${crypto.randomUUID()}@example.test`,password=crypto.randomUUID()+crypto.randomUUID();
  await page.fill('[name=name]','QA Browser Operator');await page.fill('[name=workspace_name]','QA ONLY · Browser loop');await page.fill('[name=email]',email);await page.fill('[name=password]',password);await page.click('#auth-form button[type=submit]');await page.waitForSelector('#ingest-toggle');
  check(await page.locator('.empty-state').count()>0,'honest empty state');await page.click('#ingest-toggle');await page.fill('[name=reference]','https://news.ycombinator.com/item?id=36717102');await page.click('#ingest-form button');await page.waitForSelector('.opportunity-card',{timeout:45000});check(await page.locator('.opportunity-card').count()===1,'UI ingestion populates feed');
  await page.screenshot({path:'test-results/desktop-feed.png',fullPage:true});
  await page.click('[data-detail]');await page.waitForSelector('#detail-title');check((await page.locator('#detail-content blockquote.evidence').textContent()).includes('Kanban'),'evidence view');check(await page.locator('.score-row').count()===7,'score explainability');await page.click('[data-decision=SELECTED]');await page.waitForSelector('#ingest-toggle');
  await page.click('a[href="#execution"]');await page.waitForSelector('#build-form');await page.selectOption('[name=template]','workflow');await page.fill('[name=public_title]','QA Local workflow demo');await page.fill('[name=public_summary]','Small local board with task stages and JSON file export/import. Prototype only.');await page.click('#build-form button');await page.waitForSelector('[data-publish]',{timeout:45000});
  await page.click('[data-artifact]');await page.waitForSelector('#detail-title');check((await page.locator('#detail-content').textContent()).includes('SHA256'),'artifact inspection');await page.click('#close-detail');await page.click('[data-publish]');await page.waitForSelector('[data-distribution-create]',{timeout:45000});
  const demo=await page.locator('a:has-text("Open demo")').getAttribute('href');const demoPage=await context.newPage();await demoPage.goto(BASE+demo);await demoPage.fill('[name=task]','Check a real demand signal');await demoPage.click('button:has-text("Tambah tugas")');check(await demoPage.locator('#tasks p').count()===1,'demo adds task');await demoPage.selectOption('#tasks select','Doing');check(await demoPage.locator('#tasks select').inputValue()==='Doing','demo state transition');const [download]=await Promise.all([demoPage.waitForEvent('download'),demoPage.click('#export-tasks')]);check(download.suggestedFilename()==='workflow.json','local JSON export');await demoPage.click('#tasks button');check(await demoPage.locator('#tasks p').count()===0,'demo deletion');await demoPage.locator('#import-tasks').setInputFiles({name:'board.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify([{title:'Imported task',stage:'Done'}]))});await demoPage.waitForSelector('#tasks p');check((await demoPage.locator('#tasks').textContent()).includes('Imported task'),'local JSON import');await demoPage.close();
  await page.click('[data-distribution-create]');await page.waitForSelector('[data-approve]');check(await page.locator('[data-contact]').count()===0,'no contact control before approval');await page.click('[data-approve]');await page.waitForSelector('[data-contact]');await page.click('[data-contact]');await page.waitForSelector('.badge:has-text("CONTACTED")');await page.click('a[href="#outcomes"]');await page.waitForSelector('#outcome-form');await page.fill('[name=feedback]','QA ONLY simulated reply; not a real external conversation.');await page.click('#outcome-form button');await page.waitForSelector('td .badge:has-text("FOLLOW_UP")');check(await page.locator('td .badge:has-text("FOLLOW_UP")').count()===1,'outcome frontend persistence');
  for(const route of ['opportunities','execution','distribution','outcomes','settings','feed']){await page.click(`a[href="#${route}"]`);await page.waitForSelector('#main-content h1');check(!(await page.locator('#main-content').textContent()).includes('Operasi belum berhasil'),'navigation '+route)}
  await page.click('a[href="#settings"]');await page.waitForSelector('#provider-generator-form');check(await page.locator('h2:has-text("Provider Registry")').count()===1,'provider registry UI');await page.fill('#provider-generator-form [name=provider_id]','browser-scaffold');await page.fill('#provider-generator-form [name=name]','Browser Scaffold');await page.fill('#provider-generator-form [name=docs_url]','https://example.org/docs');await page.fill('#provider-generator-form [name=credential_fields]','api_key');await page.click('#provider-generator-form button');await page.waitForSelector('[data-scaffold]');check((await page.locator('#generator-result').textContent()).includes('DOCUMENTATION_REQUIRED'),'scaffold not falsely live');await page.click('[data-scaffold]');await page.waitForSelector('#detail-title');check((await page.locator('#detail-content').textContent()).includes('credential-schema.json'),'inspect generated credential schema');await page.click('#close-detail');check(await page.locator('[data-provider-operation=health]').count()>=5,'provider health controls');
  check(await page.locator('#apify-acquisition').isVisible(),'Apify acquisition controls');check(await page.locator('#apify-actor-form [name=capability] option').count()===8,'eight logical Actor slots');check(await page.locator('#apify-acquisition input[type=password]').count()===0,'no Apify token input or masked secret');check(await page.locator('#apify-run-form button').isDisabled(),'no paid run without reviewed Actor');check((await page.locator('#apify-acquisition').textContent()).includes('platform fees may be additional'),'honest cost guard scope');
  await page.route('**/api/acquisitions/discover?*',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({data:[{actor_id:'fixtureActor',actor_name:'fixture~comments',title:'QA ONLY fixture Actor',pricing_model:'PAY_PER_EVENT',status:'DISCOVERED_NOT_VALIDATED'}],request_id:'qa-discovery'})}));await page.click('#apify-discover-form button');await page.waitForSelector('#apify-discovery-results strong');check((await page.locator('#apify-discovery-results').textContent()).includes('DISCOVERED_NOT_VALIDATED'),'discovery is not falsely production ready');await page.unroute('**/api/acquisitions/discover?*');
  check(await page.locator('#rapidapi-acquisition').isVisible(),'RapidAPI FREE-FIRST controls');check(await page.locator('#rapidapi-acquisition input[type=password]').count()===0,'no RapidAPI key form');check((await page.locator('#rapidapi-acquisition').textContent()).includes('Paid execution: BLOCKED'),'RapidAPI paid execution blocked');check(await page.locator('#rapid-run-form button').isDisabled(),'no unreviewed live request');check(await page.locator('#rapid-candidate-form option').count()===1,'one staged RapidAPI candidate');await page.click('#rapid-candidate-form button');await page.waitForSelector('[data-rapid-review]');check((await page.locator('#rapidapi-acquisition').textContent()).includes('SYNTHETIC_CONTRACT_ONLY'),'schema honesty');check(await page.locator('[data-rapid-enable]').isDisabled(),'enable blocked before actual output');check((await page.locator('#rapidapi-acquisition').textContent()).includes('UNKNOWN'),'unknown pricing not silently free');
  for(const kind of ['facebook','instagram']){await page.selectOption('#provider-form [name=kind]',kind);check(await page.locator('#provider-asset-label').isVisible(),'Meta asset input '+kind);check(await page.locator('#provider-form [name=asset_id]').getAttribute('pattern')==='[0-9]{5,32}','numeric asset schema '+kind);check(await page.locator('#provider-form [name=credential_value]').getAttribute('type')==='password','secret masked '+kind)}
  await page.selectOption('#provider-form [name=kind]','threads');check(!(await page.locator('#provider-asset-label').isVisible()),'Threads never requires Page ID');
  await page.click('a[href="#feed"]');await page.waitForSelector('#ingest-toggle');await page.click('#ingest-toggle');check(await page.locator('#fin-provider option[value=facebook]').evaluate(x=>x.disabled),'unconfigured Facebook disabled');check(await page.locator('#fin-provider option[value=instagram]').evaluate(x=>x.disabled),'unconfigured Instagram disabled');await page.selectOption('#fin-provider','github-issues');check(!(await page.locator('#fin-query-label').isVisible()),'GitHub is not keyword search');check(await page.locator('#fin-reference-label').isVisible(),'GitHub canonical reference input');check(await page.locator('#fin-evidence details').count()>0,'stored evidence review');
  await page.setViewportSize({width:390,height:844});
  for(const route of ['feed','execution','distribution','outcomes','settings']){await page.click(`a[href="#${route}"]`);await page.waitForSelector('#main-content h1');await page.waitForTimeout(250);const dims=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth}));check(dims.scroll<=dims.width+2,`mobile overflow ${route}: ${JSON.stringify(dims)}`)}
  await page.click('a[href="#feed"]');await page.waitForSelector('#feed-search');await page.screenshot({path:'test-results/mobile-feed.png',fullPage:true});await page.fill('#feed-search','impossible-zzzzzz');await page.click('#filter-submit');await page.waitForSelector('#opportunity-cards .empty-state');check((await page.locator('#opportunity-cards').textContent()).includes('Tidak ada hasil'),'filtered empty state');
  await page.route('**/api/opportunities?*',r=>r.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:{code:'INTERNAL',message:'QA injected failure',retryable:false},request_id:'qa-error'})}));await page.click('#filter-submit');await page.waitForSelector('#opportunity-cards .error-state');check((await page.locator('#opportunity-cards').textContent()).includes('QA injected failure'),'frontend error state');await page.unroute('**/api/opportunities?*');
  check(errors.length===0,'no unexpected browser errors: '+JSON.stringify(errors));await mkdir('test-results',{recursive:true});await writeFile('test-results/browser-summary.json',JSON.stringify({result:'PASS',checks,errors,desktop:'1440x1000',mobile:'390x844',commercial_records:'QA simulation only'},null,2));console.log(JSON.stringify({result:'PASS',checks,errors,desktop:'1440x1000',mobile:'390x844'},null,2));
}finally{await browser.close()}
