import { chromium } from 'playwright'
import assert from 'node:assert/strict'
import { mkdir,writeFile } from 'node:fs/promises'
const BASE=process.env.TEST_BASE_URL||'http://localhost:3000';
if(!BASE.includes('localhost')&&!process.env.ALLOW_TEST_DATA)throw Error('Browser test creates QA data; use isolated staging only.');
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const errors=[];let checks=0;
const check=(v,msg)=>{assert.ok(v,msg);checks++};
const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();
page.on('pageerror',e=>errors.push(e.message));page.on('console',msg=>{if(msg.type()==='error'&&!msg.text().includes('401 (Unauthorized)')&&!msg.text().includes('500 (Internal Server Error)'))errors.push(msg.text())});
page.on('dialog',async d=>{if(d.type()==='prompt'){await d.accept(d.message().includes('Target')?'QA ONLY browser handoff — no external contact':d.message().includes('Follow')?'2026-12-01':'QA ONLY simulated manual contact, never sent')}else await d.accept()});
try{
  await page.goto(BASE);await page.waitForSelector('#auth-form');await page.click('#auth-toggle');const email=`browser-${crypto.randomUUID()}@example.test`,password=crypto.randomUUID()+crypto.randomUUID();
  await page.fill('[name=name]','QA Browser Operator');await page.fill('[name=workspace_name]','QA ONLY · Browser loop');await page.fill('[name=email]',email);await page.fill('[name=password]',password);await page.click('#auth-form button[type=submit]');await page.waitForSelector('#ingest-toggle');
  check(await page.locator('.empty-state').count()>0,'honest empty state');await page.click('#ingest-toggle');await page.fill('[name=reference]','https://news.ycombinator.com/item?id=36717102');await page.click('#ingest-form button');await page.waitForSelector('.opportunity-card',{timeout:45000});check(await page.locator('.opportunity-card').count()===1,'UI ingestion populates feed');
  await page.screenshot({path:'test-results/desktop-feed.png',fullPage:true});
  await page.click('[data-detail]');await page.waitForSelector('#detail-title');check((await page.locator('.evidence').textContent()).includes('Kanban'),'evidence view');check(await page.locator('.score-row').count()===7,'score explainability');await page.click('[data-decision=SELECTED]');await page.waitForSelector('#ingest-toggle');
  await page.click('a[href="#execution"]');await page.waitForSelector('#build-form');await page.selectOption('[name=template]','workflow');await page.fill('[name=public_title]','QA Local workflow demo');await page.fill('[name=public_summary]','Small local board with task stages and JSON file export/import. Prototype only.');await page.click('#build-form button');await page.waitForSelector('[data-publish]',{timeout:45000});
  await page.click('[data-artifact]');await page.waitForSelector('#detail-title');check((await page.locator('#detail-content').textContent()).includes('SHA256'),'artifact inspection');await page.click('#close-detail');await page.click('[data-publish]');await page.waitForSelector('[data-distribution-create]',{timeout:45000});
  const demo=await page.locator('a:has-text("Open demo")').getAttribute('href');const demoPage=await context.newPage();await demoPage.goto(BASE+demo);await demoPage.fill('[name=task]','Check a real demand signal');await demoPage.click('button:has-text("Tambah tugas")');check(await demoPage.locator('#tasks p').count()===1,'demo adds task');await demoPage.selectOption('#tasks select','Doing');check(await demoPage.locator('#tasks select').inputValue()==='Doing','demo state transition');const [download]=await Promise.all([demoPage.waitForEvent('download'),demoPage.click('#export-tasks')]);check(download.suggestedFilename()==='workflow.json','local JSON export');await demoPage.click('#tasks button');check(await demoPage.locator('#tasks p').count()===0,'demo deletion');await demoPage.locator('#import-tasks').setInputFiles({name:'board.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify([{title:'Imported task',stage:'Done'}]))});await demoPage.waitForSelector('#tasks p');check((await demoPage.locator('#tasks').textContent()).includes('Imported task'),'local JSON import');await demoPage.close();
  await page.click('[data-distribution-create]');await page.waitForSelector('[data-approve]');check(await page.locator('[data-contact]').count()===0,'no contact control before approval');await page.click('[data-approve]');await page.waitForSelector('[data-contact]');await page.click('[data-contact]');await page.waitForSelector('.badge:has-text("CONTACTED")');await page.click('a[href="#outcomes"]');await page.waitForSelector('#outcome-form');await page.fill('[name=feedback]','QA ONLY simulated reply; not a real external conversation.');await page.click('#outcome-form button');await page.waitForSelector('td .badge:has-text("FOLLOW_UP")');check(await page.locator('td .badge:has-text("FOLLOW_UP")').count()===1,'outcome frontend persistence');
  for(const route of ['opportunities','execution','distribution','outcomes','settings','feed']){await page.click(`a[href="#${route}"]`);await page.waitForSelector('#main-content h1');check(!(await page.locator('#main-content').textContent()).includes('Operasi belum berhasil'),'navigation '+route)}
  await page.setViewportSize({width:390,height:844});
  for(const route of ['feed','execution','distribution','outcomes','settings']){await page.click(`a[href="#${route}"]`);await page.waitForSelector('#main-content h1');await page.waitForTimeout(250);const dims=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth}));check(dims.scroll<=dims.width+2,`mobile overflow ${route}: ${JSON.stringify(dims)}`)}
  await page.click('a[href="#feed"]');await page.waitForSelector('#feed-search');await page.screenshot({path:'test-results/mobile-feed.png',fullPage:true});await page.fill('#feed-search','impossible-zzzzzz');await page.click('#filter-submit');await page.waitForSelector('#opportunity-cards .empty-state');check((await page.locator('#opportunity-cards').textContent()).includes('Tidak ada hasil'),'filtered empty state');
  await page.route('**/api/opportunities?*',r=>r.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:{code:'INTERNAL',message:'QA injected failure',retryable:false},request_id:'qa-error'})}));await page.click('#filter-submit');await page.waitForSelector('#opportunity-cards .error-state');check((await page.locator('#opportunity-cards').textContent()).includes('QA injected failure'),'frontend error state');await page.unroute('**/api/opportunities?*');
  check(errors.length===0,'no unexpected browser errors: '+JSON.stringify(errors));await mkdir('test-results',{recursive:true});await writeFile('test-results/browser-summary.json',JSON.stringify({result:'PASS',checks,errors,desktop:'1440x1000',mobile:'390x844',commercial_records:'QA simulation only'},null,2));console.log(JSON.stringify({result:'PASS',checks,errors,desktop:'1440x1000',mobile:'390x844'},null,2));
}finally{await browser.close()}
