import assert from 'node:assert/strict'
import {mkdir,writeFile} from 'node:fs/promises'
const BASE=process.env.TEST_BASE_URL||'http://localhost:3000';
if(!BASE.includes('localhost')&&!process.env.ALLOW_TEST_DATA)throw Error('E2E creates QA-only commercial records. Set ALLOW_TEST_DATA deliberately for isolated staging, never production.');
let assertions=0;const check=(v,msg)=>{assert.ok(v,msg);assertions++};const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function client(){return {cookie:'',workspace:'',async req(path,method='GET',body,expected=200,extra={}){const r=await fetch(BASE+'/api'+path,{method,headers:{'Content-Type':'application/json',...(this.cookie?{Cookie:this.cookie}:{}),...(this.workspace?{'X-Workspace-ID':this.workspace}:{}),...extra},...(body?{body:JSON.stringify(body)}:{})});const b=await r.json();check(r.status===expected,`${method} ${path}: expected ${expected}, got ${r.status}: ${JSON.stringify(b)}`);check(!!b.request_id,'stable request ID');if(expected>=400)check(!!b.error?.code&&typeof b.error.retryable==='boolean','error envelope');if(r.headers.get('set-cookie'))this.cookie=r.headers.get('set-cookie').split(';')[0];return b.data||b.error},async register(name){const email=`qa-${name}-${crypto.randomUUID()}@example.test`,password=crypto.randomUUID()+crypto.randomUUID();const d=await this.req('/auth/register','POST',{email,password,name:'QA '+name,workspace_name:'QA ONLY · '+name},201);this.workspace=d.workspace_id;this.email=email;this.password=password;return d},async wait(jid,expected='SUCCEEDED'){for(let i=0;i<60;i++){const jobs=await this.req('/jobs');const j=jobs.find(j=>j.id===jid);if(j&&['SUCCEEDED','FAILED','CANCELLED'].includes(j.status)){check(j.status===expected,'job expected '+expected+': '+JSON.stringify(j));return j}await sleep(500)}throw Error('job timeout '+jid)}}}
const owner=client(),viewer=client(),outsider=client();await owner.req('/health');await client().req('/opportunities','GET',undefined,401);
await owner.register('golden');await viewer.register('viewer');await outsider.register('outsider');
const me=await owner.req('/me');check(me.role==='OWNER','owner role');
const denied=await outsider.req('/opportunities','GET',undefined,403,{'X-Workspace-ID':owner.workspace});check(denied.code==='AUTHORIZATION','workspace injection denied');
await owner.req('/members','POST',{email:viewer.email,role:'VIEWER',confirm:true});viewer.workspace=owner.workspace;check((await viewer.req('/me')).role==='VIEWER','viewer membership');await viewer.req('/signals/ingest','POST',{provider:'hacker-news',query:'need'},403);
await owner.req('/opportunities?min_score=NaN','GET',undefined,400);
await owner.req('/signals/ingest','POST',{provider:'not-a-provider',query:'tool'},400);
await owner.req('/signals/ingest','POST',{provider:'hacker-news',query:'tool'},403,{Origin:'https://evil.example'});
for(const limit of [0,-1,26,1.5,'oops',null,true])await owner.req('/signals/ingest','POST',{provider:'hacker-news',query:'tool',limit},400);
const sourceURL=process.env.TEST_SIGNAL_URL||'https://news.ycombinator.com/item?id=36717102';
const ingest=await owner.req('/signals/ingest','POST',{provider:'hacker-news',reference:sourceURL,idempotency_key:'golden-import'},202);await owner.wait(ingest.id);
const duplicateJob=await owner.req('/signals/ingest','POST',{provider:'hacker-news',reference:sourceURL,idempotency_key:'golden-import'},202);check(duplicateJob.id===ingest.id,'job idempotency');
const second=await owner.req('/signals/ingest','POST',{provider:'hacker-news',reference:sourceURL,idempotency_key:'golden-dedup'},202);await owner.wait(second.id);
const ops=await owner.req('/opportunities');check(ops.length===1,'signal and opportunity deduplicated');const op=await owner.req('/opportunities/'+ops[0].id);check(op.evidence.url===sourceURL,'canonical evidence URL');check(op.evidence.raw_text.includes('Kanban'),'real public evidence preserved');check(op.evidence.normalized_text.length>20,'normalized evidence');check(op.scores.length===1,'single versioned historical score');check(op.intent==='ACTIVE_REQUEST','active request classification');check(op.opportunity_score>0,'scored');
await outsider.req('/opportunities/'+op.id,'GET',undefined,404);
await owner.req('/executions','POST',{opportunity_id:op.id,template:'workflow',public_title:'QA Local workflow prototype',public_summary:'Local task board with JSON import and export. No customer data or outbound calls.'},409);
await owner.req('/opportunities/'+op.id+'/decision','POST',{status:'REVIEWED'});await owner.req('/opportunities/'+op.id+'/decision','POST',{status:'SELECTED'});
const build=await owner.req('/executions','POST',{opportunity_id:op.id,template:'workflow',public_title:'QA Local workflow prototype',public_summary:'Local task board with JSON import and export. No customer data or outbound calls.'},202);const built=await owner.wait(build.id);const eid=JSON.parse(built.result).execution_id;const ex=await owner.req('/executions/'+eid);check(ex.status==='VALIDATED','artifact validation');check(ex.artifacts.length===1,'durable inspectable artifact');check(ex.artifacts[0].checksum.length===64,'artifact checksum');check(!ex.artifacts[0].content.includes(op.evidence.raw_text),'raw evidence not leaked');check(JSON.parse(ex.blueprint).opportunity_id===op.id,'linked blueprint');
await owner.req('/executions/'+eid+'/publish','POST',{confirm:false},400);
const pub=await owner.req('/executions/'+eid+'/publish','POST',{confirm:true},202);const published=await owner.wait(pub.id),demo=JSON.parse(published.result).demo_url;const demoRes=await fetch(BASE+demo);check(demoRes.status===200,'reachable demo');check(demoRes.headers.get('content-security-policy').includes('sandbox'),'isolated demo');check((await demoRes.text()).includes('export-tasks'),'functional workflow artifact');
const dist=await owner.req('/distributions','POST',{execution_id:eid,target:'QA simulation only — do not contact historical source author'},201);check(dist.message.includes(sourceURL),'evidence-based message');check(dist.message.includes(demo),'demo in draft');await owner.req('/distributions/'+dist.id+'/contact','POST',{confirm:true,contact_reference:'QA simulator'},409);
await owner.req('/distributions/'+dist.id+'/approve','POST',{confirm:true});await owner.req('/distributions/'+dist.id,'PATCH',{message:dist.message+'\nQA ONLY'});await owner.req('/distributions/'+dist.id+'/contact','POST',{confirm:true,contact_reference:'QA simulator'},409);await owner.req('/distributions/'+dist.id+'/approve','POST',{confirm:true});
const contact=await owner.req('/distributions/'+dist.id+'/contact','POST',{confirm:true,contact_reference:'QA TEST ONLY: simulated manual contact; no actual message sent',next_follow_up_at:'2026-12-01'});check(contact.external_send_performed===false,'never send externally');
await owner.req('/outcomes','POST',{distribution_id:dist.id,state:'WON',revenue_minor:50000000,feedback:'QA simulation'},409);
for(const state of ['REPLIED','QUALIFIED','PROPOSAL'])await owner.req('/outcomes','POST',{distribution_id:dist.id,state,feedback:'QA ONLY simulated '+state,currency:'IDR',revenue_minor:0},201);
await owner.req('/outcomes','POST',{distribution_id:dist.id,state:'WON',revenue_minor:-1,feedback:'QA'},400);
await owner.req('/outcomes','POST',{distribution_id:dist.id,state:'WON',revenue_minor:50000000,currency:'IDR',feedback:'QA ONLY simulated revenue; NOT actual commercial result'},201);
await owner.req('/outcomes','POST',{distribution_id:dist.id,state:'LOST',feedback:'QA',loss_reason:'QA'},409);
const metrics=await owner.req('/metrics');check(metrics.revenue[0].revenue_minor===50000000,'revenue persistence in minor units');check(metrics.learning.length===4,'feedback loop from append-only outcomes');check((await owner.req('/outcomes')).length===4,'outcome history');check((await owner.req('/opportunities/'+op.id)).scores.length===1,'learning never rewrites score');check((await owner.req('/usage')).length>=3,'provider usage attribution');check((await owner.req('/audit')).some(e=>e.operation==='contact.approved'),'actor audited approval');
const invalid=await owner.req('/signals/ingest','POST',{provider:'hacker-news',reference:'http://127.0.0.1/private',idempotency_key:'invalid-source'},202);const failed=await owner.wait(invalid.id,'FAILED');check(failed.error_code==='VALIDATION','SSRF rejected in adapter, job visible');
await viewer.req('/distributions/'+dist.id+'/approve','POST',{confirm:true},403);
await owner.req('/executions/'+eid+'/unpublish','POST',{confirm:true});check((await fetch(BASE+demo)).status===404,'revocation hides old demo');

const providers=await owner.req('/providers');check(providers.registry.length>=18,'central provider registry');check(providers.registry.find(p=>p.id==='threads').status==='NOT_CONFIGURED','Threads not silently configured with App Secret');check(providers.registry.find(p=>p.id==='reddit').status==='DOCUMENTATION_REQUIRED','planned providers honest');
for(const [kind,field] of [['facebook','page_id'],['instagram','ig_user_id']]){
 await owner.req('/providers','POST',{kind,credentials:{access_token:'QA-fixture-not-live'},confirm:true},400);
 await owner.req('/providers','POST',{kind,credentials:{access_token:'QA-fixture-not-live',[field]:'https://evil.test'},confirm:true},400);
 await owner.req('/providers','POST',{kind,credentials:{access_token:'QA-fixture-not-live',[field]:'12345',app_secret:'not-accepted'},confirm:true},400);
 const configured=await owner.req('/providers','POST',{kind,credentials:{access_token:'QA-fixture-not-live',[field]:'12345'},confirm:true});check(!configured.enabled,'Meta configure never enables');
 const safe=await owner.req('/providers');check(!JSON.stringify(safe).includes('QA-fixture-not-live'),'Meta registry returns no credential');
 await owner.req('/providers/'+kind+'/enable','POST',{confirm:true},409);
 await owner.req('/signals/ingest','POST',{provider:kind,limit:1},409);
 await owner.req('/providers/'+kind,'DELETE',{confirm:true});
}
await owner.req('/providers/groq/enable','POST',{confirm:true},409);
await owner.req('/signals/ingest','POST',{provider:'threads',query:'tool'},409);
await owner.req('/opportunities/'+op.id+'/assess','POST',{provider:'groq',confirm:false},400);
await owner.req('/opportunities/'+op.id+'/assess','POST',{provider:'groq',confirm:true},409);
await viewer.req('/providers','POST',{kind:'groq',api_key:'QA-fixture-not-live',confirm:true},403);
const scaffold=await owner.req('/provider-generator','POST',{provider_id:'qa-adapter',name:'QA Adapter',family:'DISCOVERY',docs_url:'https://example.org/docs',auth_type:'BEARER',credential_fields:['api_key']},201);check(scaffold.status==='DOCUMENTATION_REQUIRED'&&Object.keys(scaffold.files).length===6,'generated scaffold not live');const persisted=await owner.req('/provider-generator/'+scaffold.id);check(persisted.checksum===scaffold.checksum,'scaffold persisted/checksummed');await outsider.req('/provider-generator/'+scaffold.id,'GET',undefined,404);await viewer.req('/provider-generator','POST',{provider_id:'viewer-adapter'},403);
await owner.req('/provider-generator','POST',{provider_id:'bad-provider',name:'Bad',family:'AI',docs_url:'http://127.0.0.1/docs'},400);
await owner.req('/providers/hacker-news/disable','POST',{confirm:false},400);await owner.req('/providers/hacker-news/disable','POST',{confirm:true});await owner.req('/signals/ingest','POST',{provider:'hacker-news',reference:sourceURL},409);check((await owner.req('/opportunities')).length===1,'disabled source history retained');check((await owner.req('/providers')).registry.find(p=>p.id==='github-issues').enabled,'independent provider remains available');await owner.req('/providers/hacker-news/enable','POST',{confirm:true},409);const validation=await owner.req('/providers/hacker-news/validate','POST',{},202);await owner.wait(validation.id);await owner.req('/providers/hacker-news/enable','POST',{confirm:true});const healthy=(await owner.req('/providers')).registry.find(p=>p.id==='hacker-news');check(healthy.enabled&&healthy.health_status==='HEALTHY'&&!!healthy.last_validation,'live public source validation and enable');
if(providers.encryption_configured){const config=await owner.req('/providers','POST',{kind:'groq',api_key:'QA-fixture-not-live',confirm:true});check(config.status==='CONFIGURED'&&!config.enabled,'configured key not enabled before validation');const status=await owner.req('/providers');check(!JSON.stringify(status).includes('QA-fixture-not-live'),'credential never returned');await owner.req('/providers/groq/enable','POST',{confirm:true},409);await owner.req('/providers/groq','DELETE',{confirm:true});check((await owner.req('/providers')).registry.find(p=>p.id==='groq').status==='NOT_CONFIGURED','revoke deletes credential');}

await owner.req('/auth/logout','POST',{});await owner.req('/me','GET',undefined,401);await owner.req('/auth/login','POST',{email:owner.email,password:owner.password});
await mkdir('test-results',{recursive:true});const state={base:BASE,email:owner.email,password:owner.password,cookie:owner.cookie,workspace:owner.workspace,opportunity_id:op.id,execution_id:eid,distribution_id:dist.id,source_url:sourceURL,assertions};await writeFile('test-results/session.json',JSON.stringify(state,null,2));
console.log(JSON.stringify({result:'PASS',assertions,source:sourceURL,evidence_published_at:op.evidence.published_at,workspace:'QA ONLY',commercial_contact:'SIMULATED; no external send',revenue:'SIMULATED; not actual revenue',publication:'immutable artifact route in tested environment; no separate customer app deployment'},null,2));
