import assert from 'node:assert/strict'
import {mkdir,writeFile} from 'node:fs/promises'
const BASE=process.env.TEST_BASE_URL||'https://ordvela.pages.dev',invitation=process.env.TEST_REGISTRATION_TOKEN;
if(!invitation)throw Error('BLOCKED: supply TEST_REGISTRATION_TOKEN via secure runtime, never in chat or source.');
if(new URL(BASE).hostname!=='ordvela.pages.dev')throw Error('This controlled smoke test targets only ORDVELA production.');
let cookie='',workspace='',checks=0;
const check=(v,label)=>{assert.ok(v,label);checks++},sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function req(path,method='GET',body,expected=200){const r=await fetch(BASE+'/api'+path,{method,headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{}),...(workspace?{'X-Workspace-ID':workspace}:{})},...(body?{body:JSON.stringify(body)}:{})});const b=await r.json();check(r.status===expected,`${method} ${path} expected ${expected}, got ${r.status} code ${b.error?.code||'none'}`);check(!!b.request_id,'request attribution');const session=r.headers.get('set-cookie');if(session){check(session.includes('HttpOnly')&&session.includes('Secure')&&session.includes('SameSite=Strict'),'secure session flags');cookie=session.split(';')[0]}return b.data||b.error}
async function wait(jid){for(let i=0;i<50;i++){const jobs=await req('/jobs'),job=jobs.find(j=>j.id===jid);if(job?.status==='SUCCEEDED')return JSON.parse(job.result);if(job?.status==='FAILED')throw Error('Job failed: '+job.error_code);await sleep(500)}throw Error('Job timeout')}
const qaName='QA ONLY · Production smoke · '+crypto.randomUUID(),email='qa-prod-'+crypto.randomUUID()+'@example.test',password=crypto.randomUUID()+crypto.randomUUID();let archived=false;
try{
 const h=await req('/health');check(h.environment==='production'&&h.database==='ready','production D1 active');await req('/opportunities','GET',undefined,401);await req('/auth/register','POST',{email,password,name:'QA ONLY',workspace_name:qaName},403);
 const reg=await req('/auth/register','POST',{email,password,name:'QA ONLY Production Smoke',workspace_name:qaName,registration_token:invitation},201);workspace=reg.workspace_id;check((await req('/me')).role==='OWNER','workspace authorization');
 const validation=await req('/providers/hacker-news/validate','POST',{},202);await wait(validation.id);check((await req('/providers')).registry.find(p=>p.id==='hacker-news').health_status==='HEALTHY','real HN provider health');
 const imported=await req('/signals/ingest','POST',{provider:'hacker-news',reference:'https://news.ycombinator.com/item?id=36717102',idempotency_key:'production-smoke-source'},202);await wait(imported.id);const feed=await req('/opportunities');check(feed.length===1,'remote evidence persistence');const op=await req('/opportunities/'+feed[0].id);check(op.evidence.raw_text.includes('Kanban')&&op.scores.length===1,'source evidence and explainable score');await req('/opportunities/'+op.id+'/decision','POST',{status:'SELECTED'});
 const build=await req('/executions','POST',{opportunity_id:op.id,template:'workflow',public_title:'ORDVELA QA verification prototype',public_summary:'QA ONLY local board prototype, not a customer implementation. No data sent externally.'},202);const built=await wait(build.id);const publish=await req('/executions/'+built.execution_id+'/publish','POST',{confirm:true},202);const published=await wait(publish.id),demo=await fetch(BASE+published.demo_url);check(demo.status===200,'live public demo on deployed application');check(demo.headers.get('Content-Security-Policy').includes('sandbox'),'sandboxed public artifact');check((await demo.text()).includes('export-tasks'),'workflow prototype inspected');
 const d=await req('/distributions','POST',{execution_id:built.execution_id,target:'QA ONLY technical test; do not contact source author'},201);await req('/distributions/'+d.id+'/contact','POST',{confirm:true,contact_reference:'QA simulation'},409);await req('/distributions/'+d.id+'/approve','POST',{confirm:true});const contact=await req('/distributions/'+d.id+'/contact','POST',{confirm:true,contact_reference:'QA ONLY simulated contact — no external message sent'});check(contact.external_send_performed===false,'no actual contact');for(const state of ['REPLIED','QUALIFIED','PROPOSAL','WON'])await req('/outcomes','POST',{distribution_id:d.id,state,revenue_minor:state==='WON'?100:0,currency:'IDR',feedback:'QA ONLY simulated '+state+'; not real customer revenue'},201);const metrics=await req('/metrics');check(metrics.learning.length===4&&metrics.revenue[0].revenue_minor===100,'append-only QA revenue and learning');
 const g=await req('/provider-generator','POST',{provider_id:'qa-prod-definition',name:'QA Definition',family:'DISCOVERY',docs_url:'https://example.org/docs',auth_type:'NONE',credential_fields:[]},201);check(g.status==='DOCUMENTATION_REQUIRED','generator cannot fabricate live adapter');
 await req('/workspaces/current/archive','POST',{confirm:true,workspace_name:qaName});archived=true;check((await fetch(BASE+published.demo_url)).status===404,'QA archive revokes public demos');
 await mkdir('test-results',{recursive:true});const summary={result:'PASS',checks,base:BASE,workspace:'QA ONLY / archived',real_evidence:'HN historical public demand',contact:'SIMULATED ONLY — no external send',revenue:'SIMULATED QA minor units; not revenue proof',cleanup:'Soft archived test workspace; history retained and public demo revoked'};await writeFile('test-results/production-summary.json',JSON.stringify(summary,null,2));console.log(JSON.stringify(summary,null,2));
}finally{if(workspace&&!archived){try{await req('/workspaces/current/archive','POST',{confirm:true,workspace_name:qaName});console.log('Failed-test QA workspace soft archived.')}catch{console.log('QA cleanup incomplete; manual owner review needed.')}}}
