import {test} from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {Miniflare,convertV4MiniflareOptions} from 'miniflare'
import {generateProvider,REGISTRY,providerFailureState,requireEnabled,registryStatus,credential} from '../src/providers'
import {ThreadsSource,GroqAdapter,normalizeEvidence,validateAssessment,seal,providerJSON} from '../src/adapters'
import {stmt,one} from '../src/db'
import {enqueue,runJobs} from '../src/jobs'

test('registry identities unique and implemented adapters documented',()=>{assert.equal(new Set(REGISTRY.map(p=>p.id)).size,REGISTRY.length);for(const p of REGISTRY.filter(p=>p.implementation!=='PLANNED'))assert.ok(p.docs_url.startsWith('https://'));assert.deepEqual(REGISTRY.find(p=>p.id==='threads')!.scopes,['threads_basic','threads_keyword_search'])})
test('generator creates six bounded files, never guesses API endpoints',async()=>{const a=await generateProvider({provider_id:'example-provider',name:'Example Provider',family:'DISCOVERY',docs_url:'https://example.org/docs',auth_type:'BEARER',credential_fields:['api_key']});assert.equal(Object.keys(a.files).length,6);assert.equal(a.status,'DOCUMENTATION_REQUIRED');assert.ok(a.files['adapter.ts'].includes("throw Error('DOCUMENTATION_REQUIRED')"));assert.equal(a.checksum.length,64);assert.ok(a.files['credential-schema.json'].includes('writeOnly'));assert.equal(a.validation.no_network_execution,true)})
test('generator rejects executable name, private URLs, credentials as schema values and invalid URLs',async()=>{const base={provider_id:'example-provider',name:'Example',family:'DISCOVERY',docs_url:'https://example.org/docs'};for(const v of [{name:'x\nalert(1)'},{docs_url:'http://127.0.0.1/docs'},{docs_url:'https://u:password@example.org/docs'},{docs_url:'invalid'},{credential_fields:['API_KEY=secret']},{provider_id:'../injected'}])await assert.rejects(()=>generateProvider({...base,...v}))})
test('source normalization includes provenance hash and raw evidence',async()=>{const n=await normalizeEvidence({external_id:'fixture:1',provider:'fixture',url:'https://example.org/public',author:'author',published_at:'2026-01-01',raw_text:'Need a workflow tool',verified:true,metadata:{}});for(const f of ['source','provider','externalId','canonicalUrl','authorRef','publishedAt','retrievedAt','title','body','language','engagement','metadata','evidence','rawReference','contentHash'])assert.ok(f in n);assert.equal(n.contentHash.length,64);assert.equal(n.evidence.text,'Need a workflow tool')})
test('Threads contract uses official endpoint and normalizes only allowed source URLs',async()=>{const original=fetch;let called='';try{globalThis.fetch=async(u)=>{called=String(u);return Response.json({data:[{id:'123',text:'Need an app',permalink:'https://www.threads.com/@example/post/abc',timestamp:'2026-01-01',username:'example',media_type:'TEXT'}]})};const a=await new ThreadsSource('fixture-token').collect({query:'need'});assert.ok(called.startsWith('https://graph.threads.com/v1.0/keyword_search?'));assert.equal(a[0].external_id,'threads:123');assert.ok(a[0].metadata.scope);globalThis.fetch=async()=>Response.json({data:[{id:'123',text:'Need',permalink:'http://localhost/private',timestamp:'x'}]});await assert.rejects(()=>new ThreadsSource('fixture').collect({query:'need'}));}finally{globalThis.fetch=original}})
test('HTTP auth failure classified safely, rate and timeout state explicit',async()=>{const original=fetch;try{globalThis.fetch=async()=>Response.json({error:{message:'secret credential must not leak'}},{status:401});await assert.rejects(()=>providerJSON('https://example.org'),(e:any)=>e.code==='AUTHENTICATION'&&!e.message.includes('secret'));assert.equal(providerFailureState('AUTHENTICATION'),'AUTH_ERROR');assert.equal(providerFailureState('RATE_LIMIT'),'RATE_LIMITED');assert.equal(providerFailureState('TIMEOUT'),'UNAVAILABLE')}finally{globalThis.fetch=original}})
test('assessment requires exact source quotes and constrained template',()=>{const base={problem:'Need a board',desired_outcome:'Simpler workflow',recommended_action:'Review hypothesis',template:'workflow',evidence_quotes:['Need a tool']};assert.equal(validateAssessment(base,'Need a tool for local tasks').score_modified,false);assert.throws(()=>validateAssessment({...base,evidence_quotes:['Budget $5000']},'Need a tool'));assert.throws(()=>validateAssessment({...base,template:'run-arbitrary-code'},'Need a tool'))})
test('Groq contract validates model and rejects hallucinated response evidence',async()=>{const original=fetch;try{globalThis.fetch=async()=>Response.json({data:[{id:'model-test'}]});await new GroqAdapter().validate('fixture-key','model-test');await assert.rejects(()=>new GroqAdapter().validate('fixture-key','missing-model'));globalThis.fetch=async()=>Response.json({model:'model-test',choices:[{message:{content:JSON.stringify({problem:'Need a board',desired_outcome:'Local flow',recommended_action:'Review',template:'workflow',evidence_quotes:['Need a tool']})}}],usage:{prompt_tokens:20,completion_tokens:50}});const a=await new GroqAdapter().assess('fixture-key','model-test','Need a tool for local tasks');assert.equal(a.input_tokens,20);assert.equal(a.output_tokens,50);assert.equal(a.result.score_modified,false);globalThis.fetch=async()=>Response.json({choices:[{message:{content:'not JSON'}}]});await assert.rejects(()=>new GroqAdapter().assess('fixture','model','Need a tool'));}finally{globalThis.fetch=original}})
test('durable provider lifecycle validates/enables, rotates/revokes, isolates workspaces and blocks disabled sources',async()=>{
 const mf=new Miniflare(convertV4MiniflareOptions({modules:true,script:'export default {fetch(){return new Response("ok")}}',d1Databases:['DB'],compatibilityDate:'2026-03-01'}));const original=fetch;
 try{const db=await mf.getD1Database('DB') as any,env={DB:db,CREDENTIAL_MASTER_KEY:'test-master'};for(const file of ['0001_initial.sql','0002_provider_registry.sql'])await db.exec(readFileSync(new URL('../migrations/'+file,import.meta.url),'utf8').replace(/\n/g,' '));await db.batch([stmt(db,'INSERT INTO users VALUES (?,?,?,?,?)','u','test@example.test','Test','hash',Date.now()),stmt(db,'INSERT INTO workspaces (id,name,created_at) VALUES (?,?,?)','w','QA',Date.now()),stmt(db,'INSERT INTO workspaces (id,name,created_at) VALUES (?,?,?)','other','Other',Date.now())]);
 const pid='w:groq',revision=Date.now();await stmt(db,"INSERT INTO providers (id,workspace_id,kind,status,credential_cipher,updated_at,config) VALUES (?,?,?,'CONFIGURED',?,?,?)",pid,'w','groq',await seal(JSON.stringify({api_key:'fixture-key'}),env.CREDENTIAL_MASTER_KEY),revision,JSON.stringify({model:'model-test'})).run();await assert.rejects(()=>requireEnabled(env,'w','groq'));globalThis.fetch=async()=>Response.json({data:[{id:'model-test'}]});const j=await enqueue(env,'w','u','r','PROVIDER_VALIDATE',{provider_id:pid,provider_kind:'groq',revision},'validate-1');await runJobs(env,'w');assert.equal((await one(db,'SELECT status FROM jobs WHERE id=?',j.id)).status,'SUCCEEDED');assert.equal((await one(db,'SELECT status FROM providers WHERE id=?',pid)).status,'HEALTHY');await stmt(db,"UPDATE providers SET enabled=1,status='ENABLED' WHERE id=?",pid).run();assert.ok(await requireEnabled(env,'w','groq'));const reg=await registryStatus(env,'w');assert.ok(!JSON.stringify(reg).includes('fixture-key'));assert.equal((await registryStatus(env,'other')).find(p=>p.id==='groq').status,'NOT_CONFIGURED');assert.equal(await credential(env,await one(db,'SELECT * FROM providers WHERE id=?',pid)),'fixture-key');
 await stmt(db,"INSERT INTO providers (id,workspace_id,kind,status,updated_at,enabled) VALUES ('w:hacker-news','w','hacker-news','DISABLED',1,0)").run();await assert.rejects(()=>requireEnabled(env,'w','hacker-news'));assert.equal((await requireEnabled(env,'w','github-issues')).enabled,1);
 await stmt(db,"UPDATE providers SET credential_cipher=NULL,enabled=0,status='NOT_CONFIGURED',updated_at=updated_at+1 WHERE id=?",pid).run();await assert.rejects(async()=>credential(env,await one(db,'SELECT * FROM providers WHERE id=?',pid)));const stale=await enqueue(env,'w','u','r','PROVIDER_VALIDATE',{provider_id:pid,provider_kind:'groq',revision},'stale');await runJobs(env,'w');assert.equal((await one(db,'SELECT status FROM jobs WHERE id=?',stale.id)).status,'FAILED');
 }finally{globalThis.fetch=original;await mf.dispose()}
})
