import {test} from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {Miniflare,convertV4MiniflareOptions} from 'miniflare'
import {RapidApiAdapter,rapidBounds,rapidCandidate,rapidSecret,freePolicy,zeroCostGate,RAPID_SOURCE_SLOTS} from '../src/rapidapi'
import {configureRapid,reviewRapid,configureFreePolicy,rapidConfig,rapidLifecycle,createRapidAcquisition,rapidRegistry,rapidHistory,cancelRapid,rapidAcquisitionStep} from '../src/rapid-acquisition'
import {acquisitionRoute,providerEvaluations} from '../src/acquisition-routing'
import {stmt,one,all} from '../src/db'
import {runJobs,ingest} from '../src/jobs'
import {registryStatus,requireEnabled,validateProvider} from '../src/providers'
import {digest} from '../src/core'
import app from '../src/index'

// Synthetic fixtures only: no real RapidAPI requests, subscriptions, charges or revenue.
const KEY='fixture-rapidapi-key-not-live',VIDEO='abcdefghijk',CANDIDATE='ytjar-yt-api-comments'
const rawRows=[{commentId:'c1',contentText:'I need a workflow app for our barber team',authorText:'fixture'},{commentId:'c2',contentText:'Beautiful music today',authorText:'fixture2'}]
function bounds(){return {query:'https://www.youtube.com/watch?v='+VIDEO,max_requests:1,max_items:5,max_spend:0,currency:'IDR',timeout_ms:5000,date_from:new Date(Date.now()-7*86400000).toISOString().slice(0,10),date_to:new Date().toISOString().slice(0,10)}}
function policy(extra:any={}){return {pricing_model:'FREEMIUM',plan_name:'SYNTHETIC',subscription_confirmed:true,hard_limit_no_overage:true,all_billing_dimensions_covered:true,free_requests:2,period_end:Date.now()+86400000,reference:'https://rapidapi.com/ytjar/api/yt-api/pricing',...extra}}
function mocked(options:any={}){let count=0;const calls:any[]=[];return {get count(){return count},calls,fetch:async(u:any,i:RequestInit={})=>{count++;const url=new URL(String(u));assert.equal(url.host,'yt-api.p.rapidapi.com');assert.equal(url.pathname,'/comments');assert.equal(url.searchParams.get('id'),VIDEO);assert.ok(!url.href.includes(KEY));assert.equal(i.method,'GET');assert.equal(i.redirect,'manual');const h=new Headers(i.headers);assert.equal(h.get('X-RapidAPI-Key'),KEY);assert.equal(h.get('X-RapidAPI-Host'),url.host);calls.push({url:url.href,method:i.method});if(options.timeout)throw Error(KEY);if(options.oversized)return Response.json({data:'x'.repeat(300001)});if(options.invalidJson)return new Response('invalid JSON');return Response.json(options.body??{data:options.rows??rawRows},{status:options.status??200,headers:{'x-ratelimit-requests-limit':'2','x-ratelimit-requests-remaining':String(options.remaining??1),'x-ratelimit-requests-reset':'600',...(options.headers||{})}})}}}
async function database(fn:(env:any)=>Promise<void>){const mf=new Miniflare(convertV4MiniflareOptions({modules:true,script:'export default {fetch(){return new Response("ok")}}',d1Databases:['DB'],compatibilityDate:'2026-03-01'}));try{const DB=await mf.getD1Database('DB') as any;for(const name of ['0001_initial.sql','0002_provider_registry.sql','0003_apify_acquisition.sql','0004_acquisition_provider_configs.sql'])await DB.exec(readFileSync(new URL('../migrations/'+name,import.meta.url),'utf8').replace(/\n/g,' '));await DB.batch([stmt(DB,'INSERT INTO users VALUES (?,?,?,?,?)','u','rapid@example.test','QA','hash',Date.now()),stmt(DB,"INSERT INTO workspaces (id,name,created_at) VALUES ('w','QA',?)",Date.now()),stmt(DB,"INSERT INTO workspaces (id,name,created_at) VALUES ('other','Other',?)",Date.now()),stmt(DB,"INSERT INTO workspace_members VALUES ('w','u','OWNER')"),stmt(DB,"INSERT INTO providers (id,workspace_id,kind,status,enabled,updated_at) VALUES ('w:rapidapi','w','rapidapi','CONFIGURED',0,?)",Date.now())]);await fn({DB,RAPIDAPI_KEY:KEY})}finally{await mf.dispose()}}
async function configured(env:any,w='w',p:any=policy()){let r=await configureRapid(env,w,'u',{candidate_id:CANDIDATE,confirm:true});await reviewRapid(env,w,'u',r.id,{confirm:true,terms_authorized:true,schema_reviewed:true,revision:r.revision});r=await rapidConfig(env,w,r.id);await configureFreePolicy(env,w,r.id,{confirm:true,revision:r.revision,policy:p});return rapidConfig(env,w,r.id)}
function input(r:any,key:string,extra:any={}){return {config_id:r.id,revision:r.revision,...bounds(),mode:'VALIDATION',confirm:true,authorize_request:true,idempotency_key:key,...extra}}
async function queue(env:any,r:any,key:string,extra:any={}){return createRapidAcquisition(env,'w','u','request',input(r,key,extra))}
async function enabled(env:any,r:any){r=await rapidConfig(env,'w',r.id);await rapidLifecycle(env,'w',r.id,'approve',{confirm:true,quality_acceptable:true,revision:r.revision});r=await rapidConfig(env,'w',r.id);await rapidLifecycle(env,'w',r.id,'enable',{confirm:true,revision:r.revision});await stmt(env.DB,"UPDATE providers SET enabled=1,status='ENABLED',health_status='HEALTHY',validated_at=? WHERE id='w:rapidapi'",Date.now()).run();return rapidConfig(env,'w',r.id)}

test('RapidAPI bounds enforce zero spend, one request, allowlisted public video and 10 bounded items',()=>{assert.equal(RAPID_SOURCE_SLOTS.length,8);assert.throws(()=>rapidSecret({DB:{} as any}));assert.throws(()=>rapidCandidate('evil.test'));for(const extra of [{max_requests:2},{max_spend:0.01},{max_spend:undefined},{max_items:11},{max_items:0},{timeout_ms:11000},{endpoint:'https://evil.test'},{query:'http://localhost/test'},{query:'https://www.youtube.com/watch?v='+VIDEO+'&token=secret'},{query:'https://www.youtube.com/watch?v='+VIDEO+'&v='+VIDEO},{date_from:'2026-02-30'},{date_from:'2000-01-01'}])assert.throws(()=>rapidBounds({...bounds(),...extra}));assert.equal(rapidBounds(bounds()).max_spend,0)})
test('Free-first requires actual policy attestation covering subscription hard limits every billing dimension and active quota',()=>{for(const extra of [{pricing_model:'UNKNOWN'},{pricing_model:'PAID'},{subscription_confirmed:false},{hard_limit_no_overage:false},{all_billing_dimensions_covered:false},{free_requests:0},{period_end:Date.now()-1},{reference:'https://evil.test'}])assert.throws(()=>freePolicy(policy(extra)));const p=freePolicy(policy());assert.equal(zeroCostGate(p,rapidBounds(bounds())).eligible,true);assert.equal(zeroCostGate({...p,verified_at:0},rapidBounds(bounds())).eligible,false)})
test('Adapter health is configured not healthy: missing subscription never sends a network request',async()=>{const original=fetch,m=mocked();try{globalThis.fetch=m.fetch;const adapter=new RapidApiAdapter(KEY);assert.equal((await adapter.health()).network_validated,false);assert.equal(adapter.estimate(rapidBounds(bounds())).cost_usd,null);await assert.rejects(()=>adapter.discover(rapidBounds(bounds())),(e:any)=>e.code==='PAYMENT_REQUIRED');assert.equal(m.count,0)}finally{globalThis.fetch=original}})
test('Bounded request authentication/provenance quota metadata and timestamp honesty',async()=>{const original=fetch,m=mocked();try{globalThis.fetch=m.fetch;const adapter=new RapidApiAdapter(KEY,CANDIDATE,freePolicy(policy())),b=rapidBounds(bounds()),result=await adapter.discover(b),n=await adapter.normalizeOutput(result,b,'fingerprint','job');assert.equal(n.records.length,2);assert.equal(n.records[0].external_id,'youtube:'+VIDEO+':c1');assert.equal(n.records[0].provider,'rapidapi');assert.equal(n.records[0].published_at,'');assert.equal(n.records[0].verified,false);for(const k of ['apiId','apiHost','endpoint','requestFingerprint','retrievedAt','responseStatus','responseMetadata','quotaMetadata','rawReference'])assert.ok(k in n.records[0].metadata);assert.equal(result.quotaMetadata['x-ratelimit-requests-remaining'],1);assert.ok(!JSON.stringify(n).includes(KEY));assert.equal(m.count,1)}finally{globalThis.fetch=original}})
test('Safe failures do not reflect response bodies or credentials and never mark retriable',async()=>{const original=fetch;try{for(const [status,code] of [[401,'AUTH_ERROR'],[403,'PERMISSION'],[402,'PAYMENT_REQUIRED'],[429,'RATE_LIMITED'],[500,'API_UNAVAILABLE'],[302,'PROVIDER_ERROR']] as const){globalThis.fetch=mocked({status,body:{secret:KEY}}).fetch;await assert.rejects(()=>new RapidApiAdapter(KEY,CANDIDATE,freePolicy(policy())).discover(rapidBounds(bounds())),(e:any)=>e.code===code&&!e.retryable&&!e.message.includes(KEY))}for(const o of [{timeout:true},{oversized:true},{invalidJson:true},{body:{unexpected:true}},{headers:{'x-rapidapi-mock-response':'true'}},{body:{data:[{contentText:KEY}]}}]){globalThis.fetch=mocked(o).fetch;await assert.rejects(()=>new RapidApiAdapter(KEY,CANDIDATE,freePolicy(policy())).discover(rapidBounds(bounds())),(e:any)=>!e.retryable&&!e.message.includes(KEY))}}finally{globalThis.fetch=original}})
test('Output mapping rejects mismatches private response fields invalid rows and out-of-range explicit dates',async()=>{const adapter=new RapidApiAdapter(KEY,CANDIDATE,freePolicy(policy())),b=rapidBounds(bounds()),n=await adapter.normalizeOutput({rows:[rawRows[0],{commentId:'bad',videoId:'xxxxxxxxxxx',contentText:'bad'},{commentId:'old',contentText:'Need an app',publishedAt:'2000-01-01T00:00:00Z'},{commentId:'secret',contentText:KEY}],response_status:200,quotaMetadata:{},responseMetadata:{},retrieved_at:new Date().toISOString()},b,'fp','job');assert.equal(n.records.length,1);assert.equal(n.rejected.length,3)})
test('Mock golden path reuses D1 qualification and scores, retaining non-demand evidence without opportunities',async()=>{const original=fetch,m=mocked();try{globalThis.fetch=m.fetch;await database(async env=>{const r=await configured(env),j=await queue(env,r,'first');await runJobs(env,'w');const job=await one(env.DB,'SELECT * FROM jobs WHERE id=?',j.id);assert.equal(job.status,'SUCCEEDED',job.error_message);const result=JSON.parse(job.result);assert.equal(result.evidence_count,2);assert.equal(result.qualified_count,1);assert.equal(result.unqualified_count,1);assert.equal((await one(env.DB,'SELECT COUNT(*) n FROM signals')).n,2);assert.equal((await one(env.DB,'SELECT version FROM opportunity_scores')).version,'rules-v1.0');assert.equal((await one(env.DB,'SELECT COUNT(*) n FROM evidence_receipts')).n,2);assert.equal((await rapidConfig(env,'w',r.id)).status,'VALIDATED');assert.equal((await rapidConfig(env,'w',r.id)).enabled,0);assert.equal((await queue(env,r,'first')).id,j.id);assert.equal(m.count,1);assert.ok(!JSON.stringify(await rapidHistory(env,'w')).includes(KEY))})}finally{globalThis.fetch=original}})
test('Cross-provider canonical ID dedup keeps multiple acquisition receipts without duplicate opportunity',async()=>{const original=fetch,m=mocked();try{globalThis.fetch=m.fetch;await database(async env=>{await ingest(env,{workspace_id:'w',actor_id:'u',request_id:'apify-request'},[{external_id:'youtube:'+VIDEO+':c1',url:'https://www.youtube.com/watch?v='+VIDEO+'&lc=c1',author:'fixture',published_at:'',raw_text:rawRows[0].contentText,provider:'apify',verified:false,metadata:{source:'youtube',acquisition_provider:'apify'}}]);const r=await configured(env),j=await queue(env,r,'cross');await runJobs(env,'w');const result=JSON.parse((await one(env.DB,'SELECT result FROM jobs WHERE id=?',j.id)).result);assert.equal(result.duplicate_count,1);assert.equal((await one(env.DB,'SELECT COUNT(*) n FROM opportunities')).n,1);assert.equal((await one(env.DB,'SELECT COUNT(*) n FROM signals')).n,2);assert.equal((await one(env.DB,'SELECT COUNT(*) n FROM evidence_receipts')).n,2);const evaluation=(await providerEvaluations(env,'w')).evaluations[0];assert.equal(evaluation.duplicates,1);assert.equal(evaluation.assisted_opportunities,1);assert.equal(evaluation.revenue_per_cost_usd,null);assert.equal(evaluation.roi_status,'NO_COST_DENOMINATOR')})}finally{globalThis.fetch=original}})
test('Actor-equivalent approval gates prevent enabled/paid/routine use before real usable validation',async()=>{await database(async env=>{const r=await configureRapid(env,'w','u',{candidate_id:CANDIDATE,confirm:true});await assert.rejects(()=>queue(env,r,'unreviewed'));await assert.rejects(()=>rapidLifecycle(env,'w',r.id,'enable',{confirm:true,revision:r.revision}));await assert.rejects(()=>reviewRapid(env,'other','u',r.id,{confirm:true,terms_authorized:true,schema_reviewed:true,revision:r.revision}));const status=(await registryStatus(env,'w')).find(p=>p.id==='rapidapi')!;assert.equal(status.configured,true);assert.equal(status.enabled,false);await assert.rejects(()=>validateProvider(env,'w',{kind:'rapidapi'}));await assert.rejects(()=>requireEnabled(env,'w','rapidapi'));})})
test('Concurrent idempotent admissions reserve global quota exactly once, no copied workspace allowance',async()=>{const original=fetch,m=mocked();try{globalThis.fetch=m.fetch;await database(async env=>{const p=policy({free_requests:1}),r=await configured(env,'w',p),other=await configured(env,'other',p),[a,b]=await Promise.all([queue(env,r,'race'),queue(env,r,'race')]);assert.equal(a.id,b.id);assert.equal((await one(env.DB,'SELECT reserved FROM provider_quota_budgets')).reserved,1);assert.equal((await one(env.DB,'SELECT COUNT(*) n FROM jobs')).n,1);await assert.rejects(()=>createRapidAcquisition(env,'other','u','request',input(other,'no-quota')),(e:any)=>e.code==='QUOTA_EXCEEDED');await runJobs(env,'w');assert.equal(m.count,1)})}finally{globalThis.fetch=original}})
test('Timeout and crashed start stay UNKNOWN: retries never issue a second provider request',async()=>{const original=fetch,m=mocked({timeout:true});try{globalThis.fetch=m.fetch;await database(async env=>{const r=await configured(env),j=await queue(env,r,'timeout');await runJobs(env,'w');assert.equal((await one(env.DB,'SELECT phase FROM acquisition_runs')).phase,'UNKNOWN');assert.equal(m.count,1);await stmt(env.DB,"UPDATE jobs SET status='QUEUED',next_run_at=0 WHERE id=?",j.id).run();await runJobs(env,'w');assert.equal(m.count,1);assert.equal((await one(env.DB,'SELECT phase FROM acquisition_runs')).phase,'UNKNOWN');await assert.rejects(()=>cancelRapid(env,'w',j.id));})}finally{globalThis.fetch=original}})
test('Crash-safe received normalization buffer resumes ingestion without a second external request',async()=>{const original=fetch,m=mocked();try{globalThis.fetch=m.fetch;await database(async env=>{const r=await configured(env),j=await queue(env,r,'recover'),job=await one(env.DB,'SELECT * FROM jobs WHERE id=?',j.id);await assert.rejects(()=>rapidAcquisitionStep(env,job,async()=>{throw Error('synthetic DB crash')}));assert.equal((await one(env.DB,'SELECT phase FROM acquisition_runs')).phase,'RECEIVED');await rapidAcquisitionStep(env,job,ingest);assert.equal(m.count,1);assert.equal((await one(env.DB,'SELECT COUNT(*) n FROM opportunities')).n,1)})}finally{globalThis.fetch=original}})
test('Malformed/all-invalid/empty outputs and cancellation do not fabricate live output validation',async()=>{const original=fetch;try{for(const rows of [[],[{garbage:true}]]){const m=mocked({rows});globalThis.fetch=m.fetch;await database(async env=>{const r=await configured(env),j=await queue(env,r,'output');await runJobs(env,'w');const job=await one(env.DB,'SELECT * FROM jobs WHERE id=?',j.id);assert.equal(job.status,rows.length?'FAILED':'SUCCEEDED');assert.equal((await rapidConfig(env,'w',r.id)).validated_at,null);assert.equal((await one(env.DB,'SELECT COUNT(*) n FROM opportunities')).n,0);assert.equal(m.count,1)})}const m=mocked();globalThis.fetch=m.fetch;await database(async env=>{const r=await configured(env),j=await queue(env,r,'cancel');await cancelRapid(env,'w',j.id);await runJobs(env,'w');assert.equal(m.count,0);assert.equal((await one(env.DB,'SELECT reserved FROM provider_quota_budgets')).reserved,1)})}finally{globalThis.fetch=original}})
test('Confirmed quota exhaustion STOP, terminal quota faults no retry, official provider remains usable',async()=>{const original=fetch,m=mocked({remaining:0});try{globalThis.fetch=m.fetch;await database(async env=>{const r=await configured(env),j=await queue(env,r,'quota');await runJobs(env,'w');const live=await enabled(env,r);await assert.rejects(()=>queue(env,live,'no-overage',{mode:'LIVE'}),(e:any)=>e.code==='QUOTA_EXCEEDED');assert.equal(m.count,1);assert.equal((await requireEnabled(env,'w','hacker-news')).enabled,1);assert.equal((await one(env.DB,'SELECT available FROM provider_quota_budgets')).available,1)})}finally{globalThis.fetch=original}})
test('Dispatch rechecks policy expiry and workspace disable before sending even approved validation',async()=>{const original=fetch,m=mocked();try{globalThis.fetch=m.fetch;for(const disable of [true,false])await database(async env=>{const r=await configured(env),j=await queue(env,r,'changed');if(disable)await stmt(env.DB,"UPDATE providers SET status='DISABLED' WHERE id='w:rapidapi'").run();else{const snapshot=JSON.parse((await one(env.DB,'SELECT snapshot FROM acquisition_runs')).snapshot);snapshot.policy.verified_at=0;await stmt(env.DB,'UPDATE acquisition_runs SET snapshot=? WHERE job_id=?',JSON.stringify(snapshot),j.id).run()}await runJobs(env,'w');assert.equal((await one(env.DB,'SELECT status FROM jobs WHERE id=?',j.id)).status,'FAILED');assert.equal(m.count,0)})}finally{globalThis.fetch=original}})

test('Global secret guard rejects unrelated generator payload and URL, without logging key or body',async()=>{await database(async env=>{const session='secret-guard-session';await stmt(env.DB,'INSERT INTO sessions VALUES (?,?,?)',await digest(session),'u',Date.now()+60000).run();const logs:string[]=[],original=console.error;try{console.error=(...x:any[])=>{logs.push(x.join(' '))};for(const [path,body] of [['/provider-generator',{provider_id:'safe',name:KEY,docs_url:'https://rapidapi.com',credential_fields:[]}],['/provider-evaluations?secret='+KEY,undefined]] as const){const r=await app.request('https://ordvela.test/api'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',Cookie:'ordvela_session='+session},...(body?{body:JSON.stringify(body)}:{})},env);assert.equal(r.status,400);assert.ok(!(await r.text()).includes(KEY))}assert.ok(!logs.join('').includes(KEY));assert.equal((await one(env.DB,'SELECT COUNT(*) n FROM provider_scaffolds')).n,0)}finally{console.error=original}})})

test('FREE-FIRST router cannot silently execute or fall back to paid/unknown sources',async()=>{await database(async env=>{await configureRapid(env,'w','u',{candidate_id:CANDIDATE,confirm:true});const route=await acquisitionRoute(env,'w',{capability:'youtube-comments',max_spend:0});assert.equal(route.recommended,null);assert.equal(route.paid_fallback,false);assert.equal(route.automatic_execution,false);const publicRoute=await acquisitionRoute(env,'w',{capability:'public-item',max_spend:0});assert.equal(publicRoute.recommended.provider,'hacker-news');await assert.rejects(()=>acquisitionRoute(env,'w',{capability:'youtube-comments',max_spend:1}));})})
test('Authenticated APIs: key absent from metadata DB/errors/logs, OWNER isolation and unknown hosts rejected',async()=>{const original=fetch,m=mocked();try{globalThis.fetch=m.fetch;await database(async env=>{const session='fixture-session';await stmt(env.DB,'INSERT INTO sessions VALUES (?,?,?)',await digest(session),'u',Date.now()+60000).run();const pending:Promise<any>[]=[];const ctx={waitUntil(p:Promise<any>){pending.push(p)},passThroughOnException(){}};const req=async(path:string,b?:any,status=200,auth=true)=>{const r=await app.request('https://ordvela.test/api'+path,{method:b?'POST':'GET',headers:{'Content-Type':'application/json',...(auth?{Cookie:'ordvela_session='+session}:{})},...(b?{body:JSON.stringify(b)}:{})},env,ctx as any);assert.equal(r.status,status,path);const raw=await r.text();assert.ok(!raw.includes(KEY));await Promise.all(pending.splice(0));return JSON.parse(raw).data};await req('/rapidapi',undefined,401,false);await req('/rapidapi/configs',{candidate_id:CANDIDATE,confirm:true},201);await req('/rapidapi/configs',{candidate_id:CANDIDATE,host:'evil.test',confirm:true},400);await req('/rapidapi/configs',{candidate_id:KEY,confirm:true},400);const r=await req('/rapidapi');assert.equal(r.runtime_configured,true);assert.equal(r.paid_execution,'BLOCKED');await req('/workspaces/current/archive',{confirm:true,workspace_name:'QA'});for(const table of ['provider_configs','provider_quota_budgets','acquisition_runs','jobs','providers','audit_events'])assert.ok(!JSON.stringify(await all(env.DB,'SELECT * FROM '+table)).includes(KEY));assert.equal(m.count,0)})}finally{globalThis.fetch=original}})
