import { Fault, text, choice, digest, now } from './core'
import { Env, one, all, stmt } from './db'
import { Evidence, HNSource, GitHubSource, providerJSON, unseal, normalizeEvidence, GroqAdapter, OpenAIAdapter, ThreadsSource } from './adapters'
export type ProviderFamily = 'DISCOVERY'|'AI'|'EXECUTION'|'DISTRIBUTION'|'INFRASTRUCTURE'
export type ProviderManifest = {id:string;name:string;family:ProviderFamily;version:string;capabilities:string[];auth_type:string;credential_fields:string[];docs_url:string;setup_url:string;scopes:string[];implementation:'ADAPTER'|'BUILTIN'|'PLANNED';setup:string;rate_limit:string;default_model?:string}
export const REGISTRY:ProviderManifest[] = [
  {id:'hacker-news',name:'Hacker News',family:'DISCOVERY',version:'1.0',capabilities:['search','public-item'],auth_type:'NONE',credential_fields:[],docs_url:'https://hn.algolia.com/api',setup_url:'https://hn.algolia.com/api',scopes:[],implementation:'ADAPTER',setup:'Public Ask HN search or canonical item URL. No credential needed.',rate_limit:'Bounded locally: 5 records/run; provider limits may vary.'},
  {id:'github-issues',name:'GitHub Issues',family:'DISCOVERY',version:'1.0',capabilities:['public-issue'],auth_type:'NONE',credential_fields:[],docs_url:'https://docs.github.com/en/rest/issues/issues#get-an-issue',setup_url:'https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api',scopes:[],implementation:'ADAPTER',setup:'Public issue URL only; no private repository access.',rate_limit:'Unauthenticated REST: 60 requests/hour per originating IP; shared edge IP may be constrained.'},
  {id:'groq',name:'Groq',family:'AI',version:'1.0',capabilities:['models','evidence-assessment'],auth_type:'BEARER',credential_fields:['api_key'],docs_url:'https://console.groq.com/docs/api-reference',setup_url:'https://console.groq.com/keys',scopes:[],implementation:'ADAPTER',setup:'Create/rotate a Groq API key, save via encrypted workspace configuration, validate, enable. Default openai/gpt-oss-20b verified in active models; optional model must be returned by /models.',rate_limit:'Account/model-specific; check Groq console. ORDVELA caps 60 jobs/hour/workspace and 50k recorded AI tokens/day.',default_model:'openai/gpt-oss-20b'},
  {id:'openai',name:'OpenAI',family:'AI',version:'1.0',capabilities:['models'],auth_type:'BEARER',credential_fields:['api_key'],docs_url:'https://platform.openai.com/docs/api-reference/models',setup_url:'https://platform.openai.com/api-keys',scopes:[],implementation:'ADAPTER',setup:'API key credential validation only. Generation intentionally not enabled in this release.',rate_limit:'Account/project-specific; see provider console.'},
  {id:'threads',name:'Threads',family:'DISCOVERY',version:'1.0',capabilities:['keyword-search'],auth_type:'USER_ACCESS_TOKEN',credential_fields:['access_token'],docs_url:'https://developers.facebook.com/documentation/threads/keyword-search',setup_url:'https://developers.facebook.com/apps/',scopes:['threads_basic','threads_keyword_search'],implementation:'ADAPTER',setup:'Use Threads app ID and corresponding secret only during OAuth in your Meta app, not as an access token. Obtain a Threads USER access token via authorized tester/Graph API Explorer. Public keyword search requires approved permission; unapproved apps search only authenticated-user posts. Exposed secrets must be rotated. No publishing/contact scopes requested.',rate_limit:'Official: 2,200 nonempty keyword queries per rolling 24h per user across apps.'},
  {id:'rules-v1.0',name:'Explainable scoring',family:'AI',version:'1.0',capabilities:['extract','score'],auth_type:'NONE',credential_fields:[],docs_url:'https://github.com/Sparkmind-obp-off/Ordvela/blob/main/docs/34_SCORING_MODEL.md',setup_url:'',scopes:[],implementation:'BUILTIN',setup:'Deterministic evidence rules; no provider keys. No automatic retraining.',rate_limit:'Included in bounded ingestion jobs.'},
  {id:'template-build',name:'Constrained templates',family:'EXECUTION',version:'1.0',capabilities:['blueprint','build','validate'],auth_type:'NONE',credential_fields:[],docs_url:'https://github.com/Sparkmind-obp-off/Ordvela/blob/main/docs/36_EXECUTION_TEMPLATE_SPEC.md',setup_url:'',scopes:[],implementation:'BUILTIN',setup:'Intake, efficiency calculator, workflow JSON. Not autonomous code execution.',rate_limit:'60 jobs/hour/workspace.'},
  {id:'cloudflare-pages',name:'Cloudflare Pages',family:'INFRASTRUCTURE',version:'1.0',capabilities:['hosted-artifact'],auth_type:'DEPLOY_RUNTIME',credential_fields:[],docs_url:'https://developers.cloudflare.com/pages/',setup_url:'https://dash.cloudflare.com/',scopes:[],implementation:'BUILTIN',setup:'Application deployed using BYOK Wrangler. Per-opportunity artifacts published through this application; no separate customer project or runtime token used.',rate_limit:'Cloudflare account limits.'},
  {id:'messaging',name:'Manual handoff',family:'DISTRIBUTION',version:'1.0',capabilities:['draft','approve','record'],auth_type:'NONE',credential_fields:[],docs_url:'https://github.com/Sparkmind-obp-off/Ordvela/blob/main/docs/24_DISTRIBUTION_LAYER.md',setup_url:'',scopes:[],implementation:'BUILTIN',setup:'Human approves. Human sends. System records. No external send API.',rate_limit:'No autonomous outreach.'},
  ...([{id:'reddit',name:'Reddit',docs:'https://www.reddit.com/dev/api/'},{id:'web-search',name:'Web / Search',docs:''},{id:'x',name:'X',docs:'https://docs.x.com/'},{id:'facebook',name:'Facebook',docs:'https://developers.facebook.com/docs/graph-api/'},{id:'instagram',name:'Instagram',docs:'https://developers.facebook.com/docs/instagram-platform/'},{id:'jobs',name:'Jobs / Freelance',docs:''},{id:'email',name:'Email',docs:''},{id:'whatsapp',name:'WhatsApp',docs:'https://developers.facebook.com/docs/whatsapp/cloud-api/'},{id:'cloudflare-workers',name:'Cloudflare Workers independent jobs',docs:'https://developers.cloudflare.com/workers/'}].map(p=>({id:p.id,name:p.name,family:(['email','whatsapp'].includes(p.id)?'DISTRIBUTION':p.id==='cloudflare-workers'?'INFRASTRUCTURE':'DISCOVERY') as ProviderFamily,version:'0.0',capabilities:[],auth_type:'DOCUMENTATION_REQUIRED',credential_fields:[],docs_url:p.docs,setup_url:p.docs,scopes:[],implementation:'PLANNED' as const,setup:'Select a concrete officially documented API and access plan before implementing. No undocumented endpoints or credentials accepted.',rate_limit:'DOCUMENTATION_REQUIRED'})))
]
export function manifest(kind:string) { const m=REGISTRY.find(p=>p.id===kind);if(!m)throw new Fault('VALIDATION','Provider tidak terdaftar');return m }
export async function registryStatus(env:Env,w:string) {
  const rows=await all(env.DB,'SELECT id,kind,status,enabled,version,config,validated_at,health_checked_at,health_status,error_code,error_message,updated_at,credential_cipher IS NOT NULL AS credential_configured FROM providers WHERE workspace_id=?',w)
  const usage=await all(env.DB,'SELECT provider,SUM(units) units,COALESCE(SUM(input_tokens),0) input_tokens,COALESCE(SUM(output_tokens),0) output_tokens FROM usage_events WHERE workspace_id=? GROUP BY provider',w)
  return REGISTRY.map(m=>{const row=rows.find(r=>r.kind===m.id),base=m.implementation==='PLANNED'?'DOCUMENTATION_REQUIRED':m.auth_type==='NONE'||m.auth_type==='DEPLOY_RUNTIME'?'ENABLED':'NOT_CONFIGURED';return {...m,resource_id:row?.id || `${w}:${m.id}`,status:row?.status || base,enabled:row?!!row.enabled:base==='ENABLED',configured:m.implementation!=='PLANNED'&&(!m.credential_fields.length||!!row?.credential_configured),health_status:row?.health_status || 'NOT_CHECKED',last_validation:row?.validated_at || null,last_health_check:row?.health_checked_at || null,error_code:row?.error_code || null,error_message:row?.error_message || null,config:row?JSON.parse(row.config):{},usage:usage.find(u=>u.provider===m.id)||{units:0,input_tokens:0,output_tokens:0}}})
}
export async function requireEnabled(env:Env,w:string,kind:string) {
  const m=manifest(kind)
  if(m.implementation==='PLANNED')throw new Fault('CONFLICT','DOCUMENTATION_REQUIRED: provider belum diimplementasikan',409)
  let p=await one(env.DB,'SELECT * FROM providers WHERE workspace_id=? AND kind=?',w,kind)
  if(!p&&!m.credential_fields.length){await stmt(env.DB,"INSERT OR IGNORE INTO providers (id,workspace_id,kind,status,updated_at,enabled,version) VALUES (?,?,?,'ENABLED',?,1,?)",`${w}:${kind}`,w,kind,now(),m.version).run();p=await one(env.DB,'SELECT * FROM providers WHERE workspace_id=? AND kind=?',w,kind)}
  if(p && !p.enabled)throw new Fault('CONFLICT','Provider dinonaktifkan; validate dan enable di Settings',409)
  if(m.credential_fields.length && (!p?.credential_cipher || !p.enabled || !['ENABLED','HEALTHY'].includes(p.status)))throw new Fault('CONFLICT','Provider belum tervalidasi/enabled',409)
  return p
}
export async function credential(env:Env,p:any):Promise<string> {
  if(!p?.credential_cipher)throw new Fault('CONFLICT','Provider credential belum dikonfigurasi',409)
  const decoded=await unseal(p.credential_cipher,env.CREDENTIAL_MASTER_KEY||'')
  if(decoded.startsWith('{')) { const v=JSON.parse(decoded);return v.api_key||v.access_token||'' }
  return decoded // backwards-compatible V0 encrypted API key
}
export async function validateProvider(env:Env,w:string,p:any) {
  const m=manifest(p.kind)
  if(m.implementation==='PLANNED')throw new Fault('CONFLICT','DOCUMENTATION_REQUIRED',409)
  if(p.kind==='hacker-news'){await new HNSource().collect({reference:'https://news.ycombinator.com/item?id=36717102'});return {health:'HEALTHY',capability:'public-item'}}
  if(p.kind==='github-issues'){await new GitHubSource().collect({reference:'https://github.com/microsoft/vscode/issues/1'});return {health:'HEALTHY',capability:'public-issue'}}
  if(p.kind==='groq') { const model=JSON.parse(p.config||'{}').model || m.default_model;await new GroqAdapter().validate(await credential(env,p),model);return {health:'HEALTHY',model,capability:'credential-and-model-access'} }
  if(p.kind==='openai') {await new OpenAIAdapter().validate(await credential(env,p));return {health:'HEALTHY',capability:'models-only'}}
  if(p.kind==='threads') {await new ThreadsSource(await credential(env,p)).collect({query:'software'});return {health:'HEALTHY',capability:'keyword-endpoint',public_scope:'NOT_INDEPENDENTLY_VERIFIED; depends on Meta approval'}}
  await one(env.DB,'SELECT 1');return {health:'HEALTHY',capability:'deterministic-runtime'}
}
export async function collectFromProvider(env:Env,w:string,input:any) {
  const p=await requireEnabled(env,w,input.provider)
  const source=input.provider==='hacker-news'?new HNSource():input.provider==='github-issues'?new GitHubSource():input.provider==='threads'?new ThreadsSource(await credential(env,p)):null
  if(!source)throw new Fault('VALIDATION','Provider bukan discovery adapter')
  return Promise.all((await source.collect(input)).map(normalizeEvidence))
}
export function providerFailureState(code:string) {return code==='AUTHENTICATION'?'AUTH_ERROR':code==='RATE_LIMIT'?'RATE_LIMITED':code==='TIMEOUT'?'UNAVAILABLE':'DEGRADED'}
export async function observeFailure(env:Env,w:string,kind:string,e:Fault,revision?:number) {
  await stmt(env.DB,'UPDATE providers SET status=?,health_status=?,error_code=?,error_message=?,health_checked_at=? WHERE workspace_id=? AND kind=? AND (? IS NULL OR updated_at=?)',providerFailureState(e.code),providerFailureState(e.code),e.code,e.message,now(),w,kind,revision??null,revision??null).run()
}
// Generator returns inspectable, non-executable scaffolds. Never registers arbitrary host/network code.
export async function generateProvider(input:any) {
  const pid=text(input.provider_id,'provider_id',60),name=text(input.name,'name',100),family=choice(input.family,'family',['DISCOVERY','AI','EXECUTION','DISTRIBUTION','INFRASTRUCTURE'])
  if(!/^[a-z][a-z0-9-]+$/.test(pid))throw new Fault('VALIDATION','provider_id gunakan huruf kecil, angka, dash')
  if(!/^[\p{L}\p{N} ._-]+$/u.test(name))throw new Fault('VALIDATION','Nama provider hanya karakter teks sederhana')
  const docs=text(input.docs_url,'docs_url',500);let url:URL
  try{url=new URL(docs)}catch{throw new Fault('VALIDATION','URL dokumentasi tidak valid')}
  if(url.protocol!=='https:'||url.username||url.password||url.search||url.hash||/^\d|localhost/i.test(url.hostname))throw new Fault('VALIDATION','URL dokumentasi HTTPS publik tanpa credential/query diperlukan')
  const fields=input.credential_fields||[];if(!Array.isArray(fields)||fields.length>10||fields.some((f:any)=>typeof f!=='string'||!/^[a-z][a-z0-9_]{1,50}$/.test(f)))throw new Fault('VALIDATION','Credential schema hanya nama field, bukan nilai secret')
  const definition={provider_id:pid,name,family,version:'0.1.0',docs_url:docs,auth_type:choice(input.auth_type||'DOCUMENTATION_REQUIRED','auth_type',['NONE','BEARER','OAUTH2','DOCUMENTATION_REQUIRED']),credential_fields:fields,capabilities:['DOCUMENTATION_REQUIRED'],status:'DOCUMENTATION_REQUIRED'}
  const adapter=`// ${name.replace(/[\r\n]/g,' ')} — scaffold only; official endpoints must be reviewed.\nexport class Adapter {\n providerId=${JSON.stringify(pid)}; providerVersion='0.1.0';\n configure(){throw Error('Use encrypted workspace credential service');}\n validateCredentials(){throw Error('DOCUMENTATION_REQUIRED');}\n healthCheck(){throw Error('DOCUMENTATION_REQUIRED');}\n fetch(){throw Error('DOCUMENTATION_REQUIRED');}\n normalize(){throw Error('Implement and test normalized source contract');}\n getUsage(){return {units:0,cost:null};}\n revoke(){throw Error('Use workspace credential revocation service');}\n}\n`
  const files={'manifest.json':JSON.stringify(definition,null,2),'credential-schema.json':JSON.stringify({type:'object',properties:Object.fromEntries(fields.map((f:string)=>[f,{type:'string',writeOnly:true}])),required:fields,additionalProperties:false},null,2),'adapter.ts':adapter,'fixtures.json':JSON.stringify({status:'DOCUMENTATION_REQUIRED',sample_response:null}),'adapter.test.ts':`import assert from 'node:assert/strict';\nimport { Adapter } from './adapter';\nconst a=new Adapter();\nassert.equal(a.providerId,${JSON.stringify(pid)});\nassert.throws(()=>a.fetch(),/DOCUMENTATION_REQUIRED/);\nassert.throws(()=>a.validateCredentials(),/DOCUMENTATION_REQUIRED/);\n`,'SETUP.md':`# ${name}\nStatus: DOCUMENTATION_REQUIRED / SCAFFOLD ONLY\nOfficial source: ${docs}\nCredential field names: ${fields.join(', ')||'none specified'}\nReview auth/scopes/endpoints/pagination/rate limits and response fixtures before runtime integration. Do not put secret values in this bundle. No API paths guessed. No scaffold marked live.\n`}
  return {definition,files,checksum:await digest(JSON.stringify(files)),validation:{safe_id:true,no_network_execution:true,secret_values_accepted:false},status:'DOCUMENTATION_REQUIRED'}
}
